/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.help.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HelpItem service. Represents a row in the &quot;Help_HelpItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.nero.help.model.impl.HelpItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.nero.help.model.impl.HelpItemImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HelpItem
 * @generated
 */
@ProviderType
public interface HelpItemModel extends BaseModel<HelpItem> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a help item model instance should use the {@link HelpItem} interface instead.
	 */

	/**
	 * Returns the primary key of this help item.
	 *
	 * @return the primary key of this help item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this help item.
	 *
	 * @param primaryKey the primary key of this help item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this help item.
	 *
	 * @return the item ID of this help item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this help item.
	 *
	 * @param itemId the item ID of this help item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the category ID of this help item.
	 *
	 * @return the category ID of this help item
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this help item.
	 *
	 * @param categoryId the category ID of this help item
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the item name of this help item.
	 *
	 * @return the item name of this help item
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this help item.
	 *
	 * @param itemName the item name of this help item
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the video url of this help item.
	 *
	 * @return the video url of this help item
	 */
	@AutoEscape
	public String getVideoURL();

	/**
	 * Sets the video url of this help item.
	 *
	 * @param videoURL the video url of this help item
	 */
	public void setVideoURL(String videoURL);

	/**
	 * Returns the video description of this help item.
	 *
	 * @return the video description of this help item
	 */
	@AutoEscape
	public String getVideoDescription();

	/**
	 * Sets the video description of this help item.
	 *
	 * @param videoDescription the video description of this help item
	 */
	public void setVideoDescription(String videoDescription);

	/**
	 * Returns the manual of this help item.
	 *
	 * @return the manual of this help item
	 */
	@AutoEscape
	public String getManual();

	/**
	 * Sets the manual of this help item.
	 *
	 * @param manual the manual of this help item
	 */
	public void setManual(String manual);

	/**
	 * Returns the position of this help item.
	 *
	 * @return the position of this help item
	 */
	public int getPosition();

	/**
	 * Sets the position of this help item.
	 *
	 * @param position the position of this help item
	 */
	public void setPosition(int position);

	/**
	 * Returns the language of this help item.
	 *
	 * @return the language of this help item
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this help item.
	 *
	 * @param language the language of this help item
	 */
	public void setLanguage(String language);

	/**
	 * Returns the is management of this help item.
	 *
	 * @return the is management of this help item
	 */
	public boolean getIsManagement();

	/**
	 * Returns <code>true</code> if this help item is is management.
	 *
	 * @return <code>true</code> if this help item is is management; <code>false</code> otherwise
	 */
	public boolean isIsManagement();

	/**
	 * Sets whether this help item is is management.
	 *
	 * @param isManagement the is management of this help item
	 */
	public void setIsManagement(boolean isManagement);

	@Override
	public HelpItem cloneWithOriginalValues();

}