/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.help.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.help.model.HelpItemRole;
import com.weprode.nero.help.model.HelpItemRoleModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the HelpItemRole service. Represents a row in the &quot;Help_HelpItemRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HelpItemRoleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HelpItemRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HelpItemRoleImpl
 * @generated
 */
public class HelpItemRoleModelImpl
	extends BaseModelImpl<HelpItemRole> implements HelpItemRoleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a help item role model instance should use the <code>HelpItemRole</code> interface instead.
	 */
	public static final String TABLE_NAME = "Help_HelpItemRole";

	public static final Object[][] TABLE_COLUMNS = {
		{"helpItemRoleId", Types.BIGINT}, {"itemId", Types.BIGINT},
		{"roleId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("helpItemRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("itemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Help_HelpItemRole (helpItemRoleId LONG not null primary key,itemId LONG,roleId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Help_HelpItemRole";

	public static final String ORDER_BY_JPQL =
		" ORDER BY helpItemRole.helpItemRoleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Help_HelpItemRole.helpItemRoleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ITEMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HELPITEMROLEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public HelpItemRoleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _helpItemRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHelpItemRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _helpItemRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HelpItemRole.class;
	}

	@Override
	public String getModelClassName() {
		return HelpItemRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HelpItemRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HelpItemRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HelpItemRole, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((HelpItemRole)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HelpItemRole, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HelpItemRole, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(HelpItemRole)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HelpItemRole, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HelpItemRole, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, HelpItemRole>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			HelpItemRole.class.getClassLoader(), HelpItemRole.class,
			ModelWrapper.class);

		try {
			Constructor<HelpItemRole> constructor =
				(Constructor<HelpItemRole>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<HelpItemRole, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<HelpItemRole, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<HelpItemRole, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<HelpItemRole, Object>>();
		Map<String, BiConsumer<HelpItemRole, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<HelpItemRole, ?>>();

		attributeGetterFunctions.put(
			"helpItemRoleId", HelpItemRole::getHelpItemRoleId);
		attributeSetterBiConsumers.put(
			"helpItemRoleId",
			(BiConsumer<HelpItemRole, Long>)HelpItemRole::setHelpItemRoleId);
		attributeGetterFunctions.put("itemId", HelpItemRole::getItemId);
		attributeSetterBiConsumers.put(
			"itemId", (BiConsumer<HelpItemRole, Long>)HelpItemRole::setItemId);
		attributeGetterFunctions.put("roleId", HelpItemRole::getRoleId);
		attributeSetterBiConsumers.put(
			"roleId", (BiConsumer<HelpItemRole, Long>)HelpItemRole::setRoleId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getHelpItemRoleId() {
		return _helpItemRoleId;
	}

	@Override
	public void setHelpItemRoleId(long helpItemRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_helpItemRoleId = helpItemRoleId;
	}

	@Override
	public long getItemId() {
		return _itemId;
	}

	@Override
	public void setItemId(long itemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itemId = itemId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalItemId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("itemId"));
	}

	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, HelpItemRole.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HelpItemRole toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HelpItemRole>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HelpItemRoleImpl helpItemRoleImpl = new HelpItemRoleImpl();

		helpItemRoleImpl.setHelpItemRoleId(getHelpItemRoleId());
		helpItemRoleImpl.setItemId(getItemId());
		helpItemRoleImpl.setRoleId(getRoleId());

		helpItemRoleImpl.resetOriginalValues();

		return helpItemRoleImpl;
	}

	@Override
	public HelpItemRole cloneWithOriginalValues() {
		HelpItemRoleImpl helpItemRoleImpl = new HelpItemRoleImpl();

		helpItemRoleImpl.setHelpItemRoleId(
			this.<Long>getColumnOriginalValue("helpItemRoleId"));
		helpItemRoleImpl.setItemId(this.<Long>getColumnOriginalValue("itemId"));
		helpItemRoleImpl.setRoleId(this.<Long>getColumnOriginalValue("roleId"));

		return helpItemRoleImpl;
	}

	@Override
	public int compareTo(HelpItemRole helpItemRole) {
		long primaryKey = helpItemRole.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof HelpItemRole)) {
			return false;
		}

		HelpItemRole helpItemRole = (HelpItemRole)object;

		long primaryKey = helpItemRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<HelpItemRole> toCacheModel() {
		HelpItemRoleCacheModel helpItemRoleCacheModel =
			new HelpItemRoleCacheModel();

		helpItemRoleCacheModel.helpItemRoleId = getHelpItemRoleId();

		helpItemRoleCacheModel.itemId = getItemId();

		helpItemRoleCacheModel.roleId = getRoleId();

		return helpItemRoleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HelpItemRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HelpItemRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HelpItemRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((HelpItemRole)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<HelpItemRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<HelpItemRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HelpItemRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((HelpItemRole)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, HelpItemRole>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _helpItemRoleId;
	private long _itemId;
	private long _roleId;

	public <T> T getColumnValue(String columnName) {
		Function<HelpItemRole, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((HelpItemRole)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("helpItemRoleId", _helpItemRoleId);
		_columnOriginalValues.put("itemId", _itemId);
		_columnOriginalValues.put("roleId", _roleId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("helpItemRoleId", 1L);

		columnBitmasks.put("itemId", 2L);

		columnBitmasks.put("roleId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private HelpItemRole _escapedModel;

}