/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.news.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.news.model.NewsAttachedFile;
import com.weprode.nero.news.model.NewsAttachedFileModel;
import com.weprode.nero.news.service.persistence.NewsAttachedFilePK;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NewsAttachedFile service. Represents a row in the &quot;News_NewsAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NewsAttachedFileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsAttachedFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsAttachedFileImpl
 * @generated
 */
public class NewsAttachedFileModelImpl
	extends BaseModelImpl<NewsAttachedFile> implements NewsAttachedFileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news attached file model instance should use the <code>NewsAttachedFile</code> interface instead.
	 */
	public static final String TABLE_NAME = "News_NewsAttachedFile";

	public static final Object[][] TABLE_COLUMNS = {
		{"newsId", Types.BIGINT}, {"fileId", Types.BIGINT},
		{"fileName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("newsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table News_NewsAttachedFile (newsId LONG not null,fileId LONG not null,fileName VARCHAR(75) null,primary key (newsId, fileId))";

	public static final String TABLE_SQL_DROP =
		"drop table News_NewsAttachedFile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY newsAttachedFile.id.newsId ASC, newsAttachedFile.id.fileId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY News_NewsAttachedFile.newsId ASC, News_NewsAttachedFile.fileId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NEWSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NewsAttachedFileModelImpl() {
	}

	@Override
	public NewsAttachedFilePK getPrimaryKey() {
		return new NewsAttachedFilePK(_newsId, _fileId);
	}

	@Override
	public void setPrimaryKey(NewsAttachedFilePK primaryKey) {
		setNewsId(primaryKey.newsId);
		setFileId(primaryKey.fileId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new NewsAttachedFilePK(_newsId, _fileId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((NewsAttachedFilePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return NewsAttachedFile.class;
	}

	@Override
	public String getModelClassName() {
		return NewsAttachedFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NewsAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NewsAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NewsAttachedFile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NewsAttachedFile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NewsAttachedFile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NewsAttachedFile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NewsAttachedFile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NewsAttachedFile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NewsAttachedFile>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NewsAttachedFile.class.getClassLoader(), NewsAttachedFile.class,
			ModelWrapper.class);

		try {
			Constructor<NewsAttachedFile> constructor =
				(Constructor<NewsAttachedFile>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NewsAttachedFile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NewsAttachedFile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NewsAttachedFile, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<NewsAttachedFile, Object>>();
		Map<String, BiConsumer<NewsAttachedFile, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<NewsAttachedFile, ?>>();

		attributeGetterFunctions.put("newsId", NewsAttachedFile::getNewsId);
		attributeSetterBiConsumers.put(
			"newsId",
			(BiConsumer<NewsAttachedFile, Long>)NewsAttachedFile::setNewsId);
		attributeGetterFunctions.put("fileId", NewsAttachedFile::getFileId);
		attributeSetterBiConsumers.put(
			"fileId",
			(BiConsumer<NewsAttachedFile, Long>)NewsAttachedFile::setFileId);
		attributeGetterFunctions.put("fileName", NewsAttachedFile::getFileName);
		attributeSetterBiConsumers.put(
			"fileName",
			(BiConsumer<NewsAttachedFile, String>)
				NewsAttachedFile::setFileName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getNewsId() {
		return _newsId;
	}

	@Override
	public void setNewsId(long newsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newsId = newsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNewsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("newsId"));
	}

	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileId = fileId;
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public NewsAttachedFile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NewsAttachedFile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsAttachedFileImpl newsAttachedFileImpl = new NewsAttachedFileImpl();

		newsAttachedFileImpl.setNewsId(getNewsId());
		newsAttachedFileImpl.setFileId(getFileId());
		newsAttachedFileImpl.setFileName(getFileName());

		newsAttachedFileImpl.resetOriginalValues();

		return newsAttachedFileImpl;
	}

	@Override
	public NewsAttachedFile cloneWithOriginalValues() {
		NewsAttachedFileImpl newsAttachedFileImpl = new NewsAttachedFileImpl();

		newsAttachedFileImpl.setNewsId(
			this.<Long>getColumnOriginalValue("newsId"));
		newsAttachedFileImpl.setFileId(
			this.<Long>getColumnOriginalValue("fileId"));
		newsAttachedFileImpl.setFileName(
			this.<String>getColumnOriginalValue("fileName"));

		return newsAttachedFileImpl;
	}

	@Override
	public int compareTo(NewsAttachedFile newsAttachedFile) {
		NewsAttachedFilePK primaryKey = newsAttachedFile.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NewsAttachedFile)) {
			return false;
		}

		NewsAttachedFile newsAttachedFile = (NewsAttachedFile)object;

		NewsAttachedFilePK primaryKey = newsAttachedFile.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NewsAttachedFile> toCacheModel() {
		NewsAttachedFileCacheModel newsAttachedFileCacheModel =
			new NewsAttachedFileCacheModel();

		newsAttachedFileCacheModel.newsAttachedFilePK = getPrimaryKey();

		newsAttachedFileCacheModel.newsId = getNewsId();

		newsAttachedFileCacheModel.fileId = getFileId();

		newsAttachedFileCacheModel.fileName = getFileName();

		String fileName = newsAttachedFileCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			newsAttachedFileCacheModel.fileName = null;
		}

		return newsAttachedFileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NewsAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NewsAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(NewsAttachedFile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NewsAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NewsAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NewsAttachedFile)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NewsAttachedFile>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _newsId;
	private long _fileId;
	private String _fileName;

	public <T> T getColumnValue(String columnName) {
		Function<NewsAttachedFile, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NewsAttachedFile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("newsId", _newsId);
		_columnOriginalValues.put("fileId", _fileId);
		_columnOriginalValues.put("fileName", _fileName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("newsId", 1L);

		columnBitmasks.put("fileId", 2L);

		columnBitmasks.put("fileName", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NewsAttachedFile _escapedModel;

}