/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.news.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.news.model.NewsPopulation;
import com.weprode.nero.news.model.NewsPopulationModel;
import com.weprode.nero.news.service.persistence.NewsPopulationPK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NewsPopulation service. Represents a row in the &quot;News_NewsPopulation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NewsPopulationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsPopulationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsPopulationImpl
 * @generated
 */
public class NewsPopulationModelImpl
	extends BaseModelImpl<NewsPopulation> implements NewsPopulationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news population model instance should use the <code>NewsPopulation</code> interface instead.
	 */
	public static final String TABLE_NAME = "News_NewsPopulation";

	public static final Object[][] TABLE_COLUMNS = {
		{"newsId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"roleId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("newsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table News_NewsPopulation (newsId LONG not null,groupId LONG not null,roleId LONG not null,primary key (newsId, groupId, roleId))";

	public static final String TABLE_SQL_DROP =
		"drop table News_NewsPopulation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY newsPopulation.id.newsId ASC, newsPopulation.id.groupId ASC, newsPopulation.id.roleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY News_NewsPopulation.newsId ASC, News_NewsPopulation.groupId ASC, News_NewsPopulation.roleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NEWSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROLEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NewsPopulationModelImpl() {
	}

	@Override
	public NewsPopulationPK getPrimaryKey() {
		return new NewsPopulationPK(_newsId, _groupId, _roleId);
	}

	@Override
	public void setPrimaryKey(NewsPopulationPK primaryKey) {
		setNewsId(primaryKey.newsId);
		setGroupId(primaryKey.groupId);
		setRoleId(primaryKey.roleId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new NewsPopulationPK(_newsId, _groupId, _roleId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((NewsPopulationPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return NewsPopulation.class;
	}

	@Override
	public String getModelClassName() {
		return NewsPopulation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NewsPopulation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NewsPopulation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsPopulation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NewsPopulation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NewsPopulation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NewsPopulation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NewsPopulation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NewsPopulation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NewsPopulation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<NewsPopulation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NewsPopulation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NewsPopulation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NewsPopulation, Object>>();
		Map<String, BiConsumer<NewsPopulation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NewsPopulation, ?>>();

		attributeGetterFunctions.put("newsId", NewsPopulation::getNewsId);
		attributeSetterBiConsumers.put(
			"newsId",
			(BiConsumer<NewsPopulation, Long>)NewsPopulation::setNewsId);
		attributeGetterFunctions.put("groupId", NewsPopulation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NewsPopulation, Long>)NewsPopulation::setGroupId);
		attributeGetterFunctions.put("roleId", NewsPopulation::getRoleId);
		attributeSetterBiConsumers.put(
			"roleId",
			(BiConsumer<NewsPopulation, Long>)NewsPopulation::setRoleId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getNewsId() {
		return _newsId;
	}

	@Override
	public void setNewsId(long newsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newsId = newsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNewsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("newsId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRoleId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("roleId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public NewsPopulation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NewsPopulation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsPopulationImpl newsPopulationImpl = new NewsPopulationImpl();

		newsPopulationImpl.setNewsId(getNewsId());
		newsPopulationImpl.setGroupId(getGroupId());
		newsPopulationImpl.setRoleId(getRoleId());

		newsPopulationImpl.resetOriginalValues();

		return newsPopulationImpl;
	}

	@Override
	public NewsPopulation cloneWithOriginalValues() {
		NewsPopulationImpl newsPopulationImpl = new NewsPopulationImpl();

		newsPopulationImpl.setNewsId(
			this.<Long>getColumnOriginalValue("newsId"));
		newsPopulationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		newsPopulationImpl.setRoleId(
			this.<Long>getColumnOriginalValue("roleId"));

		return newsPopulationImpl;
	}

	@Override
	public int compareTo(NewsPopulation newsPopulation) {
		NewsPopulationPK primaryKey = newsPopulation.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NewsPopulation)) {
			return false;
		}

		NewsPopulation newsPopulation = (NewsPopulation)object;

		NewsPopulationPK primaryKey = newsPopulation.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NewsPopulation> toCacheModel() {
		NewsPopulationCacheModel newsPopulationCacheModel =
			new NewsPopulationCacheModel();

		newsPopulationCacheModel.newsPopulationPK = getPrimaryKey();

		newsPopulationCacheModel.newsId = getNewsId();

		newsPopulationCacheModel.groupId = getGroupId();

		newsPopulationCacheModel.roleId = getRoleId();

		return newsPopulationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NewsPopulation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NewsPopulation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsPopulation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((NewsPopulation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NewsPopulation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					NewsPopulation.class, ModelWrapper.class);

	}

	private long _newsId;
	private long _groupId;
	private long _roleId;

	public <T> T getColumnValue(String columnName) {
		Function<NewsPopulation, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NewsPopulation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("newsId", _newsId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("roleId", _roleId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("newsId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("roleId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NewsPopulation _escapedModel;

}