/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.news.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.news.model.NewsRead;
import com.weprode.nero.news.model.NewsReadModel;
import com.weprode.nero.news.service.persistence.NewsReadPK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NewsRead service. Represents a row in the &quot;News_NewsRead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NewsReadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsReadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsReadImpl
 * @generated
 */
public class NewsReadModelImpl
	extends BaseModelImpl<NewsRead> implements NewsReadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news read model instance should use the <code>NewsRead</code> interface instead.
	 */
	public static final String TABLE_NAME = "News_NewsRead";

	public static final Object[][] TABLE_COLUMNS = {
		{"newsId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"readDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("newsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("readDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table News_NewsRead (newsId LONG not null,userId LONG not null,readDate DATE null,primary key (newsId, userId))";

	public static final String TABLE_SQL_DROP = "drop table News_NewsRead";

	public static final String ORDER_BY_JPQL =
		" ORDER BY newsRead.id.newsId ASC, newsRead.id.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY News_NewsRead.newsId ASC, News_NewsRead.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NEWSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NewsReadModelImpl() {
	}

	@Override
	public NewsReadPK getPrimaryKey() {
		return new NewsReadPK(_newsId, _userId);
	}

	@Override
	public void setPrimaryKey(NewsReadPK primaryKey) {
		setNewsId(primaryKey.newsId);
		setUserId(primaryKey.userId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new NewsReadPK(_newsId, _userId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((NewsReadPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return NewsRead.class;
	}

	@Override
	public String getModelClassName() {
		return NewsRead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NewsRead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NewsRead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsRead, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((NewsRead)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NewsRead, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NewsRead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NewsRead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NewsRead, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NewsRead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<NewsRead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NewsRead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NewsRead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NewsRead, Object>>();
		Map<String, BiConsumer<NewsRead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NewsRead, ?>>();

		attributeGetterFunctions.put("newsId", NewsRead::getNewsId);
		attributeSetterBiConsumers.put(
			"newsId", (BiConsumer<NewsRead, Long>)NewsRead::setNewsId);
		attributeGetterFunctions.put("userId", NewsRead::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<NewsRead, Long>)NewsRead::setUserId);
		attributeGetterFunctions.put("readDate", NewsRead::getReadDate);
		attributeSetterBiConsumers.put(
			"readDate", (BiConsumer<NewsRead, Date>)NewsRead::setReadDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getNewsId() {
		return _newsId;
	}

	@Override
	public void setNewsId(long newsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newsId = newsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNewsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("newsId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getReadDate() {
		return _readDate;
	}

	@Override
	public void setReadDate(Date readDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_readDate = readDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public NewsRead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NewsRead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsReadImpl newsReadImpl = new NewsReadImpl();

		newsReadImpl.setNewsId(getNewsId());
		newsReadImpl.setUserId(getUserId());
		newsReadImpl.setReadDate(getReadDate());

		newsReadImpl.resetOriginalValues();

		return newsReadImpl;
	}

	@Override
	public NewsRead cloneWithOriginalValues() {
		NewsReadImpl newsReadImpl = new NewsReadImpl();

		newsReadImpl.setNewsId(this.<Long>getColumnOriginalValue("newsId"));
		newsReadImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		newsReadImpl.setReadDate(this.<Date>getColumnOriginalValue("readDate"));

		return newsReadImpl;
	}

	@Override
	public int compareTo(NewsRead newsRead) {
		NewsReadPK primaryKey = newsRead.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NewsRead)) {
			return false;
		}

		NewsRead newsRead = (NewsRead)object;

		NewsReadPK primaryKey = newsRead.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NewsRead> toCacheModel() {
		NewsReadCacheModel newsReadCacheModel = new NewsReadCacheModel();

		newsReadCacheModel.newsReadPK = getPrimaryKey();

		newsReadCacheModel.newsId = getNewsId();

		newsReadCacheModel.userId = getUserId();

		Date readDate = getReadDate();

		if (readDate != null) {
			newsReadCacheModel.readDate = readDate.getTime();
		}
		else {
			newsReadCacheModel.readDate = Long.MIN_VALUE;
		}

		return newsReadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NewsRead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NewsRead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsRead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((NewsRead)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NewsRead>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					NewsRead.class, ModelWrapper.class);

	}

	private long _newsId;
	private long _userId;
	private Date _readDate;

	public <T> T getColumnValue(String columnName) {
		Function<NewsRead, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NewsRead)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("newsId", _newsId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("readDate", _readDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("newsId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("readDate", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NewsRead _escapedModel;

}