/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.progression.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.progression.model.ItemContent;
import com.weprode.nero.progression.model.ItemContentModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ItemContent service. Represents a row in the &quot;Progression_ItemContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ItemContentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemContentImpl
 * @generated
 */
public class ItemContentModelImpl
	extends BaseModelImpl<ItemContent> implements ItemContentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item content model instance should use the <code>ItemContent</code> interface instead.
	 */
	public static final String TABLE_NAME = "Progression_ItemContent";

	public static final Object[][] TABLE_COLUMNS = {
		{"contentId", Types.BIGINT}, {"progressionItemId", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"contentName", Types.VARCHAR},
		{"contentValue", Types.VARCHAR}, {"fileEntryId", Types.BIGINT},
		{"contentType", Types.INTEGER}, {"order_", Types.INTEGER},
		{"isToBeCompleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("contentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("progressionItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("contentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contentValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isToBeCompleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Progression_ItemContent (contentId LONG not null primary key,progressionItemId LONG,modifiedDate DATE null,contentName VARCHAR(75) null,contentValue VARCHAR(75) null,fileEntryId LONG,contentType INTEGER,order_ INTEGER,isToBeCompleted BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table Progression_ItemContent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY itemContent.order ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Progression_ItemContent.order_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRESSIONITEMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORDER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ItemContentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemContent.class;
	}

	@Override
	public String getModelClassName() {
		return ItemContent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ItemContent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ItemContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemContent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ItemContent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ItemContent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ItemContent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ItemContent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ItemContent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ItemContent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ItemContent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ItemContent.class.getClassLoader(), ItemContent.class,
			ModelWrapper.class);

		try {
			Constructor<ItemContent> constructor =
				(Constructor<ItemContent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ItemContent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ItemContent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ItemContent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ItemContent, Object>>();
		Map<String, BiConsumer<ItemContent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ItemContent, ?>>();

		attributeGetterFunctions.put("contentId", ItemContent::getContentId);
		attributeSetterBiConsumers.put(
			"contentId",
			(BiConsumer<ItemContent, Long>)ItemContent::setContentId);
		attributeGetterFunctions.put(
			"progressionItemId", ItemContent::getProgressionItemId);
		attributeSetterBiConsumers.put(
			"progressionItemId",
			(BiConsumer<ItemContent, Long>)ItemContent::setProgressionItemId);
		attributeGetterFunctions.put(
			"modifiedDate", ItemContent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ItemContent, Date>)ItemContent::setModifiedDate);
		attributeGetterFunctions.put(
			"contentName", ItemContent::getContentName);
		attributeSetterBiConsumers.put(
			"contentName",
			(BiConsumer<ItemContent, String>)ItemContent::setContentName);
		attributeGetterFunctions.put(
			"contentValue", ItemContent::getContentValue);
		attributeSetterBiConsumers.put(
			"contentValue",
			(BiConsumer<ItemContent, String>)ItemContent::setContentValue);
		attributeGetterFunctions.put(
			"fileEntryId", ItemContent::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<ItemContent, Long>)ItemContent::setFileEntryId);
		attributeGetterFunctions.put(
			"contentType", ItemContent::getContentType);
		attributeSetterBiConsumers.put(
			"contentType",
			(BiConsumer<ItemContent, Integer>)ItemContent::setContentType);
		attributeGetterFunctions.put("order", ItemContent::getOrder);
		attributeSetterBiConsumers.put(
			"order", (BiConsumer<ItemContent, Integer>)ItemContent::setOrder);
		attributeGetterFunctions.put(
			"isToBeCompleted", ItemContent::getIsToBeCompleted);
		attributeSetterBiConsumers.put(
			"isToBeCompleted",
			(BiConsumer<ItemContent, Boolean>)ItemContent::setIsToBeCompleted);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getContentId() {
		return _contentId;
	}

	@Override
	public void setContentId(long contentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentId = contentId;
	}

	@Override
	public long getProgressionItemId() {
		return _progressionItemId;
	}

	@Override
	public void setProgressionItemId(long progressionItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressionItemId = progressionItemId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgressionItemId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("progressionItemId"));
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getContentName() {
		if (_contentName == null) {
			return "";
		}
		else {
			return _contentName;
		}
	}

	@Override
	public void setContentName(String contentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentName = contentName;
	}

	@Override
	public String getContentValue() {
		if (_contentValue == null) {
			return "";
		}
		else {
			return _contentValue;
		}
	}

	@Override
	public void setContentValue(String contentValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentValue = contentValue;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public int getContentType() {
		return _contentType;
	}

	@Override
	public void setContentType(int contentType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentType = contentType;
	}

	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_order = order;
	}

	@Override
	public boolean getIsToBeCompleted() {
		return _isToBeCompleted;
	}

	@Override
	public boolean isIsToBeCompleted() {
		return _isToBeCompleted;
	}

	@Override
	public void setIsToBeCompleted(boolean isToBeCompleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isToBeCompleted = isToBeCompleted;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ItemContent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemContent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ItemContent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemContentImpl itemContentImpl = new ItemContentImpl();

		itemContentImpl.setContentId(getContentId());
		itemContentImpl.setProgressionItemId(getProgressionItemId());
		itemContentImpl.setModifiedDate(getModifiedDate());
		itemContentImpl.setContentName(getContentName());
		itemContentImpl.setContentValue(getContentValue());
		itemContentImpl.setFileEntryId(getFileEntryId());
		itemContentImpl.setContentType(getContentType());
		itemContentImpl.setOrder(getOrder());
		itemContentImpl.setIsToBeCompleted(isIsToBeCompleted());

		itemContentImpl.resetOriginalValues();

		return itemContentImpl;
	}

	@Override
	public ItemContent cloneWithOriginalValues() {
		ItemContentImpl itemContentImpl = new ItemContentImpl();

		itemContentImpl.setContentId(
			this.<Long>getColumnOriginalValue("contentId"));
		itemContentImpl.setProgressionItemId(
			this.<Long>getColumnOriginalValue("progressionItemId"));
		itemContentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		itemContentImpl.setContentName(
			this.<String>getColumnOriginalValue("contentName"));
		itemContentImpl.setContentValue(
			this.<String>getColumnOriginalValue("contentValue"));
		itemContentImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		itemContentImpl.setContentType(
			this.<Integer>getColumnOriginalValue("contentType"));
		itemContentImpl.setOrder(
			this.<Integer>getColumnOriginalValue("order_"));
		itemContentImpl.setIsToBeCompleted(
			this.<Boolean>getColumnOriginalValue("isToBeCompleted"));

		return itemContentImpl;
	}

	@Override
	public int compareTo(ItemContent itemContent) {
		int value = 0;

		if (getOrder() < itemContent.getOrder()) {
			value = -1;
		}
		else if (getOrder() > itemContent.getOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ItemContent)) {
			return false;
		}

		ItemContent itemContent = (ItemContent)object;

		long primaryKey = itemContent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemContent> toCacheModel() {
		ItemContentCacheModel itemContentCacheModel =
			new ItemContentCacheModel();

		itemContentCacheModel.contentId = getContentId();

		itemContentCacheModel.progressionItemId = getProgressionItemId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			itemContentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			itemContentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		itemContentCacheModel.contentName = getContentName();

		String contentName = itemContentCacheModel.contentName;

		if ((contentName != null) && (contentName.length() == 0)) {
			itemContentCacheModel.contentName = null;
		}

		itemContentCacheModel.contentValue = getContentValue();

		String contentValue = itemContentCacheModel.contentValue;

		if ((contentValue != null) && (contentValue.length() == 0)) {
			itemContentCacheModel.contentValue = null;
		}

		itemContentCacheModel.fileEntryId = getFileEntryId();

		itemContentCacheModel.contentType = getContentType();

		itemContentCacheModel.order = getOrder();

		itemContentCacheModel.isToBeCompleted = isIsToBeCompleted();

		return itemContentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ItemContent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ItemContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemContent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ItemContent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ItemContent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ItemContent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemContent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ItemContent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ItemContent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _contentId;
	private long _progressionItemId;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _contentName;
	private String _contentValue;
	private long _fileEntryId;
	private int _contentType;
	private int _order;
	private boolean _isToBeCompleted;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ItemContent, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ItemContent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("contentId", _contentId);
		_columnOriginalValues.put("progressionItemId", _progressionItemId);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("contentName", _contentName);
		_columnOriginalValues.put("contentValue", _contentValue);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("contentType", _contentType);
		_columnOriginalValues.put("order_", _order);
		_columnOriginalValues.put("isToBeCompleted", _isToBeCompleted);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("order_", "order");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("contentId", 1L);

		columnBitmasks.put("progressionItemId", 2L);

		columnBitmasks.put("modifiedDate", 4L);

		columnBitmasks.put("contentName", 8L);

		columnBitmasks.put("contentValue", 16L);

		columnBitmasks.put("fileEntryId", 32L);

		columnBitmasks.put("contentType", 64L);

		columnBitmasks.put("order_", 128L);

		columnBitmasks.put("isToBeCompleted", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ItemContent _escapedModel;

}