/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.progression.model.impl;

import com.weprode.nero.progression.model.ItemAttachedFile;
import com.weprode.nero.progression.service.ItemAttachedFileLocalServiceUtil;

/**
 * The extended model base implementation for the ItemAttachedFile service. Represents a row in the &quot;Progression_ItemAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemAttachedFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemAttachedFileImpl
 * @see ItemAttachedFile
 * @generated
 */
public abstract class ItemAttachedFileBaseImpl
	extends ItemAttachedFileModelImpl implements ItemAttachedFile {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item attached file model instance should use the <code>ItemAttachedFile</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ItemAttachedFileLocalServiceUtil.addItemAttachedFile(this);
		}
		else {
			ItemAttachedFileLocalServiceUtil.updateItemAttachedFile(this);
		}
	}

}