/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.progression.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.progression.model.ItemAttachedFile;
import com.weprode.nero.progression.model.ItemAttachedFileModel;
import com.weprode.nero.progression.model.ItemAttachedFileSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ItemAttachedFile service. Represents a row in the &quot;Progression_ItemAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ItemAttachedFileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemAttachedFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemAttachedFileImpl
 * @generated
 */
@JSON(strict = true)
public class ItemAttachedFileModelImpl
	extends BaseModelImpl<ItemAttachedFile> implements ItemAttachedFileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item attached file model instance should use the <code>ItemAttachedFile</code> interface instead.
	 */
	public static final String TABLE_NAME = "Progression_ItemAttachedFile";

	public static final Object[][] TABLE_COLUMNS = {
		{"itemAttachedFileId", Types.BIGINT},
		{"progressionItemId", Types.BIGINT}, {"fileEntryId", Types.BIGINT},
		{"isAudioRecording", Types.BOOLEAN}, {"isToBeCompleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("itemAttachedFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("progressionItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isAudioRecording", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isToBeCompleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Progression_ItemAttachedFile (itemAttachedFileId LONG not null primary key,progressionItemId LONG,fileEntryId LONG,isAudioRecording BOOLEAN,isToBeCompleted BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table Progression_ItemAttachedFile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY itemAttachedFile.itemAttachedFileId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Progression_ItemAttachedFile.itemAttachedFileId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ITEMATTACHEDFILEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRESSIONITEMID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ItemAttachedFile toModel(ItemAttachedFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ItemAttachedFile model = new ItemAttachedFileImpl();

		model.setItemAttachedFileId(soapModel.getItemAttachedFileId());
		model.setProgressionItemId(soapModel.getProgressionItemId());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setIsAudioRecording(soapModel.isIsAudioRecording());
		model.setIsToBeCompleted(soapModel.isIsToBeCompleted());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ItemAttachedFile> toModels(
		ItemAttachedFileSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ItemAttachedFile> models = new ArrayList<ItemAttachedFile>(
			soapModels.length);

		for (ItemAttachedFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ItemAttachedFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _itemAttachedFileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setItemAttachedFileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _itemAttachedFileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemAttachedFile.class;
	}

	@Override
	public String getModelClassName() {
		return ItemAttachedFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ItemAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ItemAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ItemAttachedFile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ItemAttachedFile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ItemAttachedFile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ItemAttachedFile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ItemAttachedFile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ItemAttachedFile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ItemAttachedFile>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ItemAttachedFile.class.getClassLoader(), ItemAttachedFile.class,
			ModelWrapper.class);

		try {
			Constructor<ItemAttachedFile> constructor =
				(Constructor<ItemAttachedFile>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ItemAttachedFile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ItemAttachedFile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ItemAttachedFile, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ItemAttachedFile, Object>>();
		Map<String, BiConsumer<ItemAttachedFile, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ItemAttachedFile, ?>>();

		attributeGetterFunctions.put(
			"itemAttachedFileId", ItemAttachedFile::getItemAttachedFileId);
		attributeSetterBiConsumers.put(
			"itemAttachedFileId",
			(BiConsumer<ItemAttachedFile, Long>)
				ItemAttachedFile::setItemAttachedFileId);
		attributeGetterFunctions.put(
			"progressionItemId", ItemAttachedFile::getProgressionItemId);
		attributeSetterBiConsumers.put(
			"progressionItemId",
			(BiConsumer<ItemAttachedFile, Long>)
				ItemAttachedFile::setProgressionItemId);
		attributeGetterFunctions.put(
			"fileEntryId", ItemAttachedFile::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<ItemAttachedFile, Long>)
				ItemAttachedFile::setFileEntryId);
		attributeGetterFunctions.put(
			"isAudioRecording", ItemAttachedFile::getIsAudioRecording);
		attributeSetterBiConsumers.put(
			"isAudioRecording",
			(BiConsumer<ItemAttachedFile, Boolean>)
				ItemAttachedFile::setIsAudioRecording);
		attributeGetterFunctions.put(
			"isToBeCompleted", ItemAttachedFile::getIsToBeCompleted);
		attributeSetterBiConsumers.put(
			"isToBeCompleted",
			(BiConsumer<ItemAttachedFile, Boolean>)
				ItemAttachedFile::setIsToBeCompleted);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getItemAttachedFileId() {
		return _itemAttachedFileId;
	}

	@Override
	public void setItemAttachedFileId(long itemAttachedFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_itemAttachedFileId = itemAttachedFileId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalItemAttachedFileId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("itemAttachedFileId"));
	}

	@JSON
	@Override
	public long getProgressionItemId() {
		return _progressionItemId;
	}

	@Override
	public void setProgressionItemId(long progressionItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressionItemId = progressionItemId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProgressionItemId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("progressionItemId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public boolean getIsAudioRecording() {
		return _isAudioRecording;
	}

	@JSON
	@Override
	public boolean isIsAudioRecording() {
		return _isAudioRecording;
	}

	@Override
	public void setIsAudioRecording(boolean isAudioRecording) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isAudioRecording = isAudioRecording;
	}

	@JSON
	@Override
	public boolean getIsToBeCompleted() {
		return _isToBeCompleted;
	}

	@JSON
	@Override
	public boolean isIsToBeCompleted() {
		return _isToBeCompleted;
	}

	@Override
	public void setIsToBeCompleted(boolean isToBeCompleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isToBeCompleted = isToBeCompleted;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ItemAttachedFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemAttachedFile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ItemAttachedFile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemAttachedFileImpl itemAttachedFileImpl = new ItemAttachedFileImpl();

		itemAttachedFileImpl.setItemAttachedFileId(getItemAttachedFileId());
		itemAttachedFileImpl.setProgressionItemId(getProgressionItemId());
		itemAttachedFileImpl.setFileEntryId(getFileEntryId());
		itemAttachedFileImpl.setIsAudioRecording(isIsAudioRecording());
		itemAttachedFileImpl.setIsToBeCompleted(isIsToBeCompleted());

		itemAttachedFileImpl.resetOriginalValues();

		return itemAttachedFileImpl;
	}

	@Override
	public ItemAttachedFile cloneWithOriginalValues() {
		ItemAttachedFileImpl itemAttachedFileImpl = new ItemAttachedFileImpl();

		itemAttachedFileImpl.setItemAttachedFileId(
			this.<Long>getColumnOriginalValue("itemAttachedFileId"));
		itemAttachedFileImpl.setProgressionItemId(
			this.<Long>getColumnOriginalValue("progressionItemId"));
		itemAttachedFileImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		itemAttachedFileImpl.setIsAudioRecording(
			this.<Boolean>getColumnOriginalValue("isAudioRecording"));
		itemAttachedFileImpl.setIsToBeCompleted(
			this.<Boolean>getColumnOriginalValue("isToBeCompleted"));

		return itemAttachedFileImpl;
	}

	@Override
	public int compareTo(ItemAttachedFile itemAttachedFile) {
		long primaryKey = itemAttachedFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ItemAttachedFile)) {
			return false;
		}

		ItemAttachedFile itemAttachedFile = (ItemAttachedFile)object;

		long primaryKey = itemAttachedFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemAttachedFile> toCacheModel() {
		ItemAttachedFileCacheModel itemAttachedFileCacheModel =
			new ItemAttachedFileCacheModel();

		itemAttachedFileCacheModel.itemAttachedFileId = getItemAttachedFileId();

		itemAttachedFileCacheModel.progressionItemId = getProgressionItemId();

		itemAttachedFileCacheModel.fileEntryId = getFileEntryId();

		itemAttachedFileCacheModel.isAudioRecording = isIsAudioRecording();

		itemAttachedFileCacheModel.isToBeCompleted = isIsToBeCompleted();

		return itemAttachedFileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ItemAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ItemAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ItemAttachedFile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ItemAttachedFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ItemAttachedFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemAttachedFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ItemAttachedFile)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ItemAttachedFile>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _itemAttachedFileId;
	private long _progressionItemId;
	private long _fileEntryId;
	private boolean _isAudioRecording;
	private boolean _isToBeCompleted;

	public <T> T getColumnValue(String columnName) {
		Function<ItemAttachedFile, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ItemAttachedFile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("itemAttachedFileId", _itemAttachedFileId);
		_columnOriginalValues.put("progressionItemId", _progressionItemId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("isAudioRecording", _isAudioRecording);
		_columnOriginalValues.put("isToBeCompleted", _isToBeCompleted);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("itemAttachedFileId", 1L);

		columnBitmasks.put("progressionItemId", 2L);

		columnBitmasks.put("fileEntryId", 4L);

		columnBitmasks.put("isAudioRecording", 8L);

		columnBitmasks.put("isToBeCompleted", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ItemAttachedFile _escapedModel;

}