/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.organization.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ClassCoursMapping service. Represents a row in the &quot;Organization_ClassCoursMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.facile.organization.model.impl.ClassCoursMappingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.facile.organization.model.impl.ClassCoursMappingImpl</code>.
 * </p>
 *
 * @author Marc Salvat
 * @see ClassCoursMapping
 * @generated
 */
@ProviderType
public interface ClassCoursMappingModel extends BaseModel<ClassCoursMapping> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a class cours mapping model instance should use the {@link ClassCoursMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this class cours mapping.
	 *
	 * @return the primary key of this class cours mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this class cours mapping.
	 *
	 * @param primaryKey the primary key of this class cours mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mapping ID of this class cours mapping.
	 *
	 * @return the mapping ID of this class cours mapping
	 */
	public long getMappingId();

	/**
	 * Sets the mapping ID of this class cours mapping.
	 *
	 * @param mappingId the mapping ID of this class cours mapping
	 */
	public void setMappingId(long mappingId);

	/**
	 * Returns the class org ID of this class cours mapping.
	 *
	 * @return the class org ID of this class cours mapping
	 */
	public long getClassOrgId();

	/**
	 * Sets the class org ID of this class cours mapping.
	 *
	 * @param classOrgId the class org ID of this class cours mapping
	 */
	public void setClassOrgId(long classOrgId);

	/**
	 * Returns the cours org ID of this class cours mapping.
	 *
	 * @return the cours org ID of this class cours mapping
	 */
	public long getCoursOrgId();

	/**
	 * Sets the cours org ID of this class cours mapping.
	 *
	 * @param coursOrgId the cours org ID of this class cours mapping
	 */
	public void setCoursOrgId(long coursOrgId);

	@Override
	public ClassCoursMapping cloneWithOriginalValues();

}