/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.schedule.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.schedule.model.SubjectGroupColor;
import com.weprode.nero.schedule.model.SubjectGroupColorModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SubjectGroupColor service. Represents a row in the &quot;Schedule_SubjectGroupColor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubjectGroupColorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectGroupColorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubjectGroupColorImpl
 * @generated
 */
public class SubjectGroupColorModelImpl
	extends BaseModelImpl<SubjectGroupColor> implements SubjectGroupColorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject group color model instance should use the <code>SubjectGroupColor</code> interface instead.
	 */
	public static final String TABLE_NAME = "Schedule_SubjectGroupColor";

	public static final Object[][] TABLE_COLUMNS = {
		{"subjectGroupColorId", Types.BIGINT}, {"subject", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"color", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("subjectGroupColorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("color", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Schedule_SubjectGroupColor (subjectGroupColorId LONG not null primary key,subject VARCHAR(75) null,groupId LONG,color VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Schedule_SubjectGroupColor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subjectGroupColor.subjectGroupColorId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Schedule_SubjectGroupColor.subjectGroupColorId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBJECT_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBJECTGROUPCOLORID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SubjectGroupColorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subjectGroupColorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubjectGroupColorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subjectGroupColorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SubjectGroupColor.class;
	}

	@Override
	public String getModelClassName() {
		return SubjectGroupColor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SubjectGroupColor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SubjectGroupColor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectGroupColor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SubjectGroupColor)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SubjectGroupColor, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SubjectGroupColor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SubjectGroupColor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SubjectGroupColor, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SubjectGroupColor, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SubjectGroupColor>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SubjectGroupColor.class.getClassLoader(), SubjectGroupColor.class,
			ModelWrapper.class);

		try {
			Constructor<SubjectGroupColor> constructor =
				(Constructor<SubjectGroupColor>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SubjectGroupColor, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SubjectGroupColor, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SubjectGroupColor, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SubjectGroupColor, Object>>();
		Map<String, BiConsumer<SubjectGroupColor, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SubjectGroupColor, ?>>();

		attributeGetterFunctions.put(
			"subjectGroupColorId", SubjectGroupColor::getSubjectGroupColorId);
		attributeSetterBiConsumers.put(
			"subjectGroupColorId",
			(BiConsumer<SubjectGroupColor, Long>)
				SubjectGroupColor::setSubjectGroupColorId);
		attributeGetterFunctions.put("subject", SubjectGroupColor::getSubject);
		attributeSetterBiConsumers.put(
			"subject",
			(BiConsumer<SubjectGroupColor, String>)
				SubjectGroupColor::setSubject);
		attributeGetterFunctions.put("groupId", SubjectGroupColor::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SubjectGroupColor, Long>)SubjectGroupColor::setGroupId);
		attributeGetterFunctions.put("color", SubjectGroupColor::getColor);
		attributeSetterBiConsumers.put(
			"color",
			(BiConsumer<SubjectGroupColor, String>)SubjectGroupColor::setColor);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSubjectGroupColorId() {
		return _subjectGroupColorId;
	}

	@Override
	public void setSubjectGroupColorId(long subjectGroupColorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subjectGroupColorId = subjectGroupColorId;
	}

	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSubject() {
		return getColumnOriginalValue("subject");
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public String getColor() {
		if (_color == null) {
			return "";
		}
		else {
			return _color;
		}
	}

	@Override
	public void setColor(String color) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_color = color;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SubjectGroupColor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SubjectGroupColor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SubjectGroupColor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubjectGroupColorImpl subjectGroupColorImpl =
			new SubjectGroupColorImpl();

		subjectGroupColorImpl.setSubjectGroupColorId(getSubjectGroupColorId());
		subjectGroupColorImpl.setSubject(getSubject());
		subjectGroupColorImpl.setGroupId(getGroupId());
		subjectGroupColorImpl.setColor(getColor());

		subjectGroupColorImpl.resetOriginalValues();

		return subjectGroupColorImpl;
	}

	@Override
	public SubjectGroupColor cloneWithOriginalValues() {
		SubjectGroupColorImpl subjectGroupColorImpl =
			new SubjectGroupColorImpl();

		subjectGroupColorImpl.setSubjectGroupColorId(
			this.<Long>getColumnOriginalValue("subjectGroupColorId"));
		subjectGroupColorImpl.setSubject(
			this.<String>getColumnOriginalValue("subject"));
		subjectGroupColorImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		subjectGroupColorImpl.setColor(
			this.<String>getColumnOriginalValue("color"));

		return subjectGroupColorImpl;
	}

	@Override
	public int compareTo(SubjectGroupColor subjectGroupColor) {
		long primaryKey = subjectGroupColor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SubjectGroupColor)) {
			return false;
		}

		SubjectGroupColor subjectGroupColor = (SubjectGroupColor)object;

		long primaryKey = subjectGroupColor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SubjectGroupColor> toCacheModel() {
		SubjectGroupColorCacheModel subjectGroupColorCacheModel =
			new SubjectGroupColorCacheModel();

		subjectGroupColorCacheModel.subjectGroupColorId =
			getSubjectGroupColorId();

		subjectGroupColorCacheModel.subject = getSubject();

		String subject = subjectGroupColorCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			subjectGroupColorCacheModel.subject = null;
		}

		subjectGroupColorCacheModel.groupId = getGroupId();

		subjectGroupColorCacheModel.color = getColor();

		String color = subjectGroupColorCacheModel.color;

		if ((color != null) && (color.length() == 0)) {
			subjectGroupColorCacheModel.color = null;
		}

		return subjectGroupColorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SubjectGroupColor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SubjectGroupColor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectGroupColor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SubjectGroupColor)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SubjectGroupColor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SubjectGroupColor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubjectGroupColor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SubjectGroupColor)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SubjectGroupColor>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _subjectGroupColorId;
	private String _subject;
	private long _groupId;
	private String _color;

	public <T> T getColumnValue(String columnName) {
		Function<SubjectGroupColor, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SubjectGroupColor)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("subjectGroupColorId", _subjectGroupColorId);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("color", _color);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("subjectGroupColorId", 1L);

		columnBitmasks.put("subject", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("color", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SubjectGroupColor _escapedModel;

}