/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.access.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.facile.access.model.AccessProfile;
import com.weprode.facile.access.model.AccessProfileModel;
import com.weprode.facile.access.service.persistence.AccessProfilePK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AccessProfile service. Represents a row in the &quot;Access_AccessProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AccessProfileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccessProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccessProfileImpl
 * @generated
 */
public class AccessProfileModelImpl
	extends BaseModelImpl<AccessProfile> implements AccessProfileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a access profile model instance should use the <code>AccessProfile</code> interface instead.
	 */
	public static final String TABLE_NAME = "Access_AccessProfile";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"accessId", Types.BIGINT},
		{"roleId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Access_AccessProfile (uuid_ VARCHAR(75) null,accessId LONG not null,roleId LONG not null,primary key (accessId, roleId))";

	public static final String TABLE_SQL_DROP =
		"drop table Access_AccessProfile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY accessProfile.id.accessId ASC, accessProfile.id.roleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Access_AccessProfile.accessId ASC, Access_AccessProfile.roleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCESSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROLEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AccessProfileModelImpl() {
	}

	@Override
	public AccessProfilePK getPrimaryKey() {
		return new AccessProfilePK(_accessId, _roleId);
	}

	@Override
	public void setPrimaryKey(AccessProfilePK primaryKey) {
		setAccessId(primaryKey.accessId);
		setRoleId(primaryKey.roleId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new AccessProfilePK(_accessId, _roleId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((AccessProfilePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return AccessProfile.class;
	}

	@Override
	public String getModelClassName() {
		return AccessProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AccessProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AccessProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccessProfile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AccessProfile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AccessProfile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AccessProfile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AccessProfile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AccessProfile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AccessProfile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AccessProfile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AccessProfile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AccessProfile, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AccessProfile, Object>>();
		Map<String, BiConsumer<AccessProfile, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AccessProfile, ?>>();

		attributeGetterFunctions.put("uuid", AccessProfile::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<AccessProfile, String>)AccessProfile::setUuid);
		attributeGetterFunctions.put("accessId", AccessProfile::getAccessId);
		attributeSetterBiConsumers.put(
			"accessId",
			(BiConsumer<AccessProfile, Long>)AccessProfile::setAccessId);
		attributeGetterFunctions.put("roleId", AccessProfile::getRoleId);
		attributeSetterBiConsumers.put(
			"roleId",
			(BiConsumer<AccessProfile, Long>)AccessProfile::setRoleId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAccessId() {
		return _accessId;
	}

	@Override
	public void setAccessId(long accessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accessId = accessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAccessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("accessId"));
	}

	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public AccessProfile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AccessProfile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AccessProfileImpl accessProfileImpl = new AccessProfileImpl();

		accessProfileImpl.setUuid(getUuid());
		accessProfileImpl.setAccessId(getAccessId());
		accessProfileImpl.setRoleId(getRoleId());

		accessProfileImpl.resetOriginalValues();

		return accessProfileImpl;
	}

	@Override
	public AccessProfile cloneWithOriginalValues() {
		AccessProfileImpl accessProfileImpl = new AccessProfileImpl();

		accessProfileImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		accessProfileImpl.setAccessId(
			this.<Long>getColumnOriginalValue("accessId"));
		accessProfileImpl.setRoleId(
			this.<Long>getColumnOriginalValue("roleId"));

		return accessProfileImpl;
	}

	@Override
	public int compareTo(AccessProfile accessProfile) {
		AccessProfilePK primaryKey = accessProfile.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AccessProfile)) {
			return false;
		}

		AccessProfile accessProfile = (AccessProfile)object;

		AccessProfilePK primaryKey = accessProfile.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AccessProfile> toCacheModel() {
		AccessProfileCacheModel accessProfileCacheModel =
			new AccessProfileCacheModel();

		accessProfileCacheModel.accessProfilePK = getPrimaryKey();

		accessProfileCacheModel.uuid = getUuid();

		String uuid = accessProfileCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			accessProfileCacheModel.uuid = null;
		}

		accessProfileCacheModel.accessId = getAccessId();

		accessProfileCacheModel.roleId = getRoleId();

		return accessProfileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AccessProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AccessProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccessProfile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AccessProfile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AccessProfile>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AccessProfile.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _accessId;
	private long _roleId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AccessProfile, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AccessProfile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("accessId", _accessId);
		_columnOriginalValues.put("roleId", _roleId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("accessId", 2L);

		columnBitmasks.put("roleId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AccessProfile _escapedModel;

}