/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.document.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.document.model.Activity;
import com.weprode.nero.document.model.ActivityModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Activity service. Represents a row in the &quot;Document_Activity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ActivityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActivityImpl
 * @generated
 */
public class ActivityModelImpl
	extends BaseModelImpl<Activity> implements ActivityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a activity model instance should use the <code>Activity</code> interface instead.
	 */
	public static final String TABLE_NAME = "Document_Activity";

	public static final Object[][] TABLE_COLUMNS = {
		{"activityId", Types.BIGINT}, {"fileEntryId", Types.BIGINT},
		{"folderId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"fileName", Types.VARCHAR},
		{"folderName", Types.VARCHAR}, {"type_", Types.INTEGER},
		{"modificationDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("activityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("folderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("folderName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("modificationDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Document_Activity (activityId LONG not null primary key,fileEntryId LONG,folderId LONG,userId LONG,groupId LONG,fileName VARCHAR(75) null,folderName VARCHAR(75) null,type_ INTEGER,modificationDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Document_Activity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY activity.activityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Document_Activity.activityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVITYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ActivityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _activityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setActivityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _activityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Activity.class;
	}

	@Override
	public String getModelClassName() {
		return Activity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Activity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Activity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Activity, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Activity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Activity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Activity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Activity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Activity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Activity.class.getClassLoader(), Activity.class,
			ModelWrapper.class);

		try {
			Constructor<Activity> constructor =
				(Constructor<Activity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Activity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Activity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Activity, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Activity, Object>>();
		Map<String, BiConsumer<Activity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Activity, ?>>();

		attributeGetterFunctions.put("activityId", Activity::getActivityId);
		attributeSetterBiConsumers.put(
			"activityId", (BiConsumer<Activity, Long>)Activity::setActivityId);
		attributeGetterFunctions.put("fileEntryId", Activity::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<Activity, Long>)Activity::setFileEntryId);
		attributeGetterFunctions.put("folderId", Activity::getFolderId);
		attributeSetterBiConsumers.put(
			"folderId", (BiConsumer<Activity, Long>)Activity::setFolderId);
		attributeGetterFunctions.put("userId", Activity::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Activity, Long>)Activity::setUserId);
		attributeGetterFunctions.put("groupId", Activity::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Activity, Long>)Activity::setGroupId);
		attributeGetterFunctions.put("fileName", Activity::getFileName);
		attributeSetterBiConsumers.put(
			"fileName", (BiConsumer<Activity, String>)Activity::setFileName);
		attributeGetterFunctions.put("folderName", Activity::getFolderName);
		attributeSetterBiConsumers.put(
			"folderName",
			(BiConsumer<Activity, String>)Activity::setFolderName);
		attributeGetterFunctions.put("type", Activity::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<Activity, Integer>)Activity::setType);
		attributeGetterFunctions.put(
			"modificationDate", Activity::getModificationDate);
		attributeSetterBiConsumers.put(
			"modificationDate",
			(BiConsumer<Activity, Date>)Activity::setModificationDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getActivityId() {
		return _activityId;
	}

	@Override
	public void setActivityId(long activityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_activityId = activityId;
	}

	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public long getFolderId() {
		return _folderId;
	}

	@Override
	public void setFolderId(long folderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_folderId = folderId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@Override
	public String getFolderName() {
		if (_folderName == null) {
			return "";
		}
		else {
			return _folderName;
		}
	}

	@Override
	public void setFolderName(String folderName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_folderName = folderName;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public Date getModificationDate() {
		return _modificationDate;
	}

	@Override
	public void setModificationDate(Date modificationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modificationDate = modificationDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Activity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Activity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Activity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ActivityImpl activityImpl = new ActivityImpl();

		activityImpl.setActivityId(getActivityId());
		activityImpl.setFileEntryId(getFileEntryId());
		activityImpl.setFolderId(getFolderId());
		activityImpl.setUserId(getUserId());
		activityImpl.setGroupId(getGroupId());
		activityImpl.setFileName(getFileName());
		activityImpl.setFolderName(getFolderName());
		activityImpl.setType(getType());
		activityImpl.setModificationDate(getModificationDate());

		activityImpl.resetOriginalValues();

		return activityImpl;
	}

	@Override
	public Activity cloneWithOriginalValues() {
		ActivityImpl activityImpl = new ActivityImpl();

		activityImpl.setActivityId(
			this.<Long>getColumnOriginalValue("activityId"));
		activityImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		activityImpl.setFolderId(this.<Long>getColumnOriginalValue("folderId"));
		activityImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		activityImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		activityImpl.setFileName(
			this.<String>getColumnOriginalValue("fileName"));
		activityImpl.setFolderName(
			this.<String>getColumnOriginalValue("folderName"));
		activityImpl.setType(this.<Integer>getColumnOriginalValue("type_"));
		activityImpl.setModificationDate(
			this.<Date>getColumnOriginalValue("modificationDate"));

		return activityImpl;
	}

	@Override
	public int compareTo(Activity activity) {
		long primaryKey = activity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Activity)) {
			return false;
		}

		Activity activity = (Activity)object;

		long primaryKey = activity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Activity> toCacheModel() {
		ActivityCacheModel activityCacheModel = new ActivityCacheModel();

		activityCacheModel.activityId = getActivityId();

		activityCacheModel.fileEntryId = getFileEntryId();

		activityCacheModel.folderId = getFolderId();

		activityCacheModel.userId = getUserId();

		activityCacheModel.groupId = getGroupId();

		activityCacheModel.fileName = getFileName();

		String fileName = activityCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			activityCacheModel.fileName = null;
		}

		activityCacheModel.folderName = getFolderName();

		String folderName = activityCacheModel.folderName;

		if ((folderName != null) && (folderName.length() == 0)) {
			activityCacheModel.folderName = null;
		}

		activityCacheModel.type = getType();

		Date modificationDate = getModificationDate();

		if (modificationDate != null) {
			activityCacheModel.modificationDate = modificationDate.getTime();
		}
		else {
			activityCacheModel.modificationDate = Long.MIN_VALUE;
		}

		return activityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Activity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Activity)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Activity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Activity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Activity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _activityId;
	private long _fileEntryId;
	private long _folderId;
	private long _userId;
	private long _groupId;
	private String _fileName;
	private String _folderName;
	private int _type;
	private Date _modificationDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Activity, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Activity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("activityId", _activityId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("folderId", _folderId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("fileName", _fileName);
		_columnOriginalValues.put("folderName", _folderName);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("modificationDate", _modificationDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("activityId", 1L);

		columnBitmasks.put("fileEntryId", 2L);

		columnBitmasks.put("folderId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("fileName", 32L);

		columnBitmasks.put("folderName", 64L);

		columnBitmasks.put("type_", 128L);

		columnBitmasks.put("modificationDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Activity _escapedModel;

}