/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.about.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.facile.about.model.UserReadVersionNote;
import com.weprode.facile.about.model.UserReadVersionNoteModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserReadVersionNote service. Represents a row in the &quot;About_UserReadVersionNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserReadVersionNoteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserReadVersionNoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserReadVersionNoteImpl
 * @generated
 */
public class UserReadVersionNoteModelImpl
	extends BaseModelImpl<UserReadVersionNote>
	implements UserReadVersionNoteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user read version note model instance should use the <code>UserReadVersionNote</code> interface instead.
	 */
	public static final String TABLE_NAME = "About_UserReadVersionNote";

	public static final Object[][] TABLE_COLUMNS = {
		{"userId", Types.BIGINT}, {"hasReadLastVersionNote", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hasReadLastVersionNote", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table About_UserReadVersionNote (userId LONG not null primary key,hasReadLastVersionNote BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table About_UserReadVersionNote";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userReadVersionNote.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY About_UserReadVersionNote.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HASREADLASTVERSIONNOTE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserReadVersionNoteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserReadVersionNote.class;
	}

	@Override
	public String getModelClassName() {
		return UserReadVersionNote.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserReadVersionNote, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserReadVersionNote, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserReadVersionNote, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserReadVersionNote)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserReadVersionNote, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserReadVersionNote, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserReadVersionNote)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserReadVersionNote, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserReadVersionNote, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UserReadVersionNote, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserReadVersionNote, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserReadVersionNote, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<UserReadVersionNote, Object>>();
		Map<String, BiConsumer<UserReadVersionNote, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<UserReadVersionNote, ?>>();

		attributeGetterFunctions.put("userId", UserReadVersionNote::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<UserReadVersionNote, Long>)
				UserReadVersionNote::setUserId);
		attributeGetterFunctions.put(
			"hasReadLastVersionNote",
			UserReadVersionNote::getHasReadLastVersionNote);
		attributeSetterBiConsumers.put(
			"hasReadLastVersionNote",
			(BiConsumer<UserReadVersionNote, Boolean>)
				UserReadVersionNote::setHasReadLastVersionNote);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public boolean getHasReadLastVersionNote() {
		return _hasReadLastVersionNote;
	}

	@Override
	public boolean isHasReadLastVersionNote() {
		return _hasReadLastVersionNote;
	}

	@Override
	public void setHasReadLastVersionNote(boolean hasReadLastVersionNote) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hasReadLastVersionNote = hasReadLastVersionNote;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalHasReadLastVersionNote() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("hasReadLastVersionNote"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, UserReadVersionNote.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserReadVersionNote toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserReadVersionNote>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserReadVersionNoteImpl userReadVersionNoteImpl =
			new UserReadVersionNoteImpl();

		userReadVersionNoteImpl.setUserId(getUserId());
		userReadVersionNoteImpl.setHasReadLastVersionNote(
			isHasReadLastVersionNote());

		userReadVersionNoteImpl.resetOriginalValues();

		return userReadVersionNoteImpl;
	}

	@Override
	public UserReadVersionNote cloneWithOriginalValues() {
		UserReadVersionNoteImpl userReadVersionNoteImpl =
			new UserReadVersionNoteImpl();

		userReadVersionNoteImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		userReadVersionNoteImpl.setHasReadLastVersionNote(
			this.<Boolean>getColumnOriginalValue("hasReadLastVersionNote"));

		return userReadVersionNoteImpl;
	}

	@Override
	public int compareTo(UserReadVersionNote userReadVersionNote) {
		long primaryKey = userReadVersionNote.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserReadVersionNote)) {
			return false;
		}

		UserReadVersionNote userReadVersionNote = (UserReadVersionNote)object;

		long primaryKey = userReadVersionNote.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserReadVersionNote> toCacheModel() {
		UserReadVersionNoteCacheModel userReadVersionNoteCacheModel =
			new UserReadVersionNoteCacheModel();

		userReadVersionNoteCacheModel.userId = getUserId();

		userReadVersionNoteCacheModel.hasReadLastVersionNote =
			isHasReadLastVersionNote();

		return userReadVersionNoteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserReadVersionNote, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserReadVersionNote, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserReadVersionNote, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UserReadVersionNote)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserReadVersionNote>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserReadVersionNote.class, ModelWrapper.class);

	}

	private long _userId;
	private boolean _hasReadLastVersionNote;

	public <T> T getColumnValue(String columnName) {
		Function<UserReadVersionNote, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserReadVersionNote)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put(
			"hasReadLastVersionNote", _hasReadLastVersionNote);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("userId", 1L);

		columnBitmasks.put("hasReadLastVersionNote", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserReadVersionNote _escapedModel;

}