/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.application.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.facile.application.model.AuthorizedSchool;
import com.weprode.facile.application.model.AuthorizedSchoolModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuthorizedSchool service. Represents a row in the &quot;Application_AuthorizedSchool&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuthorizedSchoolModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuthorizedSchoolImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuthorizedSchoolImpl
 * @generated
 */
public class AuthorizedSchoolModelImpl
	extends BaseModelImpl<AuthorizedSchool> implements AuthorizedSchoolModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a authorized school model instance should use the <code>AuthorizedSchool</code> interface instead.
	 */
	public static final String TABLE_NAME = "Application_AuthorizedSchool";

	public static final Object[][] TABLE_COLUMNS = {
		{"authorizedSchoolId", Types.BIGINT}, {"applicationId", Types.BIGINT},
		{"schoolId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("authorizedSchoolId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("schoolId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Application_AuthorizedSchool (authorizedSchoolId LONG not null primary key,applicationId LONG,schoolId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Application_AuthorizedSchool";

	public static final String ORDER_BY_JPQL =
		" ORDER BY authorizedSchool.authorizedSchoolId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Application_AuthorizedSchool.authorizedSchoolId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SCHOOLID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUTHORIZEDSCHOOLID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuthorizedSchoolModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _authorizedSchoolId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuthorizedSchoolId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _authorizedSchoolId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuthorizedSchool.class;
	}

	@Override
	public String getModelClassName() {
		return AuthorizedSchool.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuthorizedSchool, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuthorizedSchool, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuthorizedSchool, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AuthorizedSchool)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuthorizedSchool, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuthorizedSchool, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuthorizedSchool)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuthorizedSchool, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuthorizedSchool, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AuthorizedSchool, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AuthorizedSchool, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AuthorizedSchool, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<AuthorizedSchool, Object>>();
		Map<String, BiConsumer<AuthorizedSchool, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AuthorizedSchool, ?>>();

		attributeGetterFunctions.put(
			"authorizedSchoolId", AuthorizedSchool::getAuthorizedSchoolId);
		attributeSetterBiConsumers.put(
			"authorizedSchoolId",
			(BiConsumer<AuthorizedSchool, Long>)
				AuthorizedSchool::setAuthorizedSchoolId);
		attributeGetterFunctions.put(
			"applicationId", AuthorizedSchool::getApplicationId);
		attributeSetterBiConsumers.put(
			"applicationId",
			(BiConsumer<AuthorizedSchool, Long>)
				AuthorizedSchool::setApplicationId);
		attributeGetterFunctions.put("schoolId", AuthorizedSchool::getSchoolId);
		attributeSetterBiConsumers.put(
			"schoolId",
			(BiConsumer<AuthorizedSchool, Long>)AuthorizedSchool::setSchoolId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAuthorizedSchoolId() {
		return _authorizedSchoolId;
	}

	@Override
	public void setAuthorizedSchoolId(long authorizedSchoolId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_authorizedSchoolId = authorizedSchoolId;
	}

	@Override
	public long getApplicationId() {
		return _applicationId;
	}

	@Override
	public void setApplicationId(long applicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicationId = applicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("applicationId"));
	}

	@Override
	public long getSchoolId() {
		return _schoolId;
	}

	@Override
	public void setSchoolId(long schoolId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_schoolId = schoolId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSchoolId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("schoolId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AuthorizedSchool.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuthorizedSchool toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuthorizedSchool>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuthorizedSchoolImpl authorizedSchoolImpl = new AuthorizedSchoolImpl();

		authorizedSchoolImpl.setAuthorizedSchoolId(getAuthorizedSchoolId());
		authorizedSchoolImpl.setApplicationId(getApplicationId());
		authorizedSchoolImpl.setSchoolId(getSchoolId());

		authorizedSchoolImpl.resetOriginalValues();

		return authorizedSchoolImpl;
	}

	@Override
	public AuthorizedSchool cloneWithOriginalValues() {
		AuthorizedSchoolImpl authorizedSchoolImpl = new AuthorizedSchoolImpl();

		authorizedSchoolImpl.setAuthorizedSchoolId(
			this.<Long>getColumnOriginalValue("authorizedSchoolId"));
		authorizedSchoolImpl.setApplicationId(
			this.<Long>getColumnOriginalValue("applicationId"));
		authorizedSchoolImpl.setSchoolId(
			this.<Long>getColumnOriginalValue("schoolId"));

		return authorizedSchoolImpl;
	}

	@Override
	public int compareTo(AuthorizedSchool authorizedSchool) {
		long primaryKey = authorizedSchool.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuthorizedSchool)) {
			return false;
		}

		AuthorizedSchool authorizedSchool = (AuthorizedSchool)object;

		long primaryKey = authorizedSchool.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuthorizedSchool> toCacheModel() {
		AuthorizedSchoolCacheModel authorizedSchoolCacheModel =
			new AuthorizedSchoolCacheModel();

		authorizedSchoolCacheModel.authorizedSchoolId = getAuthorizedSchoolId();

		authorizedSchoolCacheModel.applicationId = getApplicationId();

		authorizedSchoolCacheModel.schoolId = getSchoolId();

		return authorizedSchoolCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AuthorizedSchool, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AuthorizedSchool, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuthorizedSchool, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AuthorizedSchool)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AuthorizedSchool>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AuthorizedSchool.class, ModelWrapper.class);

	}

	private long _authorizedSchoolId;
	private long _applicationId;
	private long _schoolId;

	public <T> T getColumnValue(String columnName) {
		Function<AuthorizedSchool, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuthorizedSchool)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("authorizedSchoolId", _authorizedSchoolId);
		_columnOriginalValues.put("applicationId", _applicationId);
		_columnOriginalValues.put("schoolId", _schoolId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("authorizedSchoolId", 1L);

		columnBitmasks.put("applicationId", 2L);

		columnBitmasks.put("schoolId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuthorizedSchool _escapedModel;

}