/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.messaging.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.weprode.nero.messaging.model.MessagingConfig;
import com.weprode.nero.messaging.service.MessagingConfigService;
import com.weprode.nero.messaging.service.MessagingConfigServiceUtil;
import com.weprode.nero.messaging.service.persistence.MessageAttachFilePersistence;
import com.weprode.nero.messaging.service.persistence.MessageContentPersistence;
import com.weprode.nero.messaging.service.persistence.MessageFinder;
import com.weprode.nero.messaging.service.persistence.MessageFolderPersistence;
import com.weprode.nero.messaging.service.persistence.MessagePersistence;
import com.weprode.nero.messaging.service.persistence.MessageRecipientsPersistence;
import com.weprode.nero.messaging.service.persistence.MessagingConfigPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the messaging config remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.weprode.nero.messaging.service.impl.MessagingConfigServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.weprode.nero.messaging.service.impl.MessagingConfigServiceImpl
 * @generated
 */
public abstract class MessagingConfigServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, MessagingConfigService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MessagingConfigService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MessagingConfigServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MessagingConfigService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		messagingConfigService = (MessagingConfigService)aopProxy;

		_setServiceUtilService(messagingConfigService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MessagingConfigService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MessagingConfig.class;
	}

	protected String getModelClassName() {
		return MessagingConfig.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = messagingConfigPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		MessagingConfigService messagingConfigService) {

		try {
			Field field = MessagingConfigServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, messagingConfigService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected MessagePersistence messagePersistence;

	@Reference
	protected MessageFinder messageFinder;

	@Reference
	protected MessageAttachFilePersistence messageAttachFilePersistence;

	@Reference
	protected MessageContentPersistence messageContentPersistence;

	@Reference
	protected MessageFolderPersistence messageFolderPersistence;

	@Reference
	protected MessageRecipientsPersistence messageRecipientsPersistence;

	@Reference
	protected com.weprode.nero.messaging.service.MessagingConfigLocalService
		messagingConfigLocalService;

	protected MessagingConfigService messagingConfigService;

	@Reference
	protected MessagingConfigPersistence messagingConfigPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		MessagingConfigServiceBaseImpl.class);

}