/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.group.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.group.model.MembershipActivity;
import com.weprode.nero.group.model.MembershipActivityModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MembershipActivity service. Represents a row in the &quot;Group_MembershipActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MembershipActivityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MembershipActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MembershipActivityImpl
 * @generated
 */
public class MembershipActivityModelImpl
	extends BaseModelImpl<MembershipActivity>
	implements MembershipActivityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a membership activity model instance should use the <code>MembershipActivity</code> interface instead.
	 */
	public static final String TABLE_NAME = "Group_MembershipActivity";

	public static final Object[][] TABLE_COLUMNS = {
		{"membershipActivityId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"actionUserId", Types.BIGINT}, {"targetUserIds", Types.VARCHAR},
		{"incoming", Types.BOOLEAN}, {"movementDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("membershipActivityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actionUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetUserIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("incoming", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("movementDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Group_MembershipActivity (membershipActivityId LONG not null primary key,groupId LONG,actionUserId LONG,targetUserIds VARCHAR(300) null,incoming BOOLEAN,movementDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Group_MembershipActivity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY membershipActivity.membershipActivityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Group_MembershipActivity.membershipActivityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MEMBERSHIPACTIVITYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MembershipActivityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _membershipActivityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMembershipActivityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _membershipActivityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MembershipActivity.class;
	}

	@Override
	public String getModelClassName() {
		return MembershipActivity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MembershipActivity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MembershipActivity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MembershipActivity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MembershipActivity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MembershipActivity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MembershipActivity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MembershipActivity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MembershipActivity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MembershipActivity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MembershipActivity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MembershipActivity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MembershipActivity, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MembershipActivity, Object>>();
		Map<String, BiConsumer<MembershipActivity, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<MembershipActivity, ?>>();

		attributeGetterFunctions.put(
			"membershipActivityId",
			MembershipActivity::getMembershipActivityId);
		attributeSetterBiConsumers.put(
			"membershipActivityId",
			(BiConsumer<MembershipActivity, Long>)
				MembershipActivity::setMembershipActivityId);
		attributeGetterFunctions.put("groupId", MembershipActivity::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MembershipActivity, Long>)
				MembershipActivity::setGroupId);
		attributeGetterFunctions.put(
			"actionUserId", MembershipActivity::getActionUserId);
		attributeSetterBiConsumers.put(
			"actionUserId",
			(BiConsumer<MembershipActivity, Long>)
				MembershipActivity::setActionUserId);
		attributeGetterFunctions.put(
			"targetUserIds", MembershipActivity::getTargetUserIds);
		attributeSetterBiConsumers.put(
			"targetUserIds",
			(BiConsumer<MembershipActivity, String>)
				MembershipActivity::setTargetUserIds);
		attributeGetterFunctions.put(
			"incoming", MembershipActivity::getIncoming);
		attributeSetterBiConsumers.put(
			"incoming",
			(BiConsumer<MembershipActivity, Boolean>)
				MembershipActivity::setIncoming);
		attributeGetterFunctions.put(
			"movementDate", MembershipActivity::getMovementDate);
		attributeSetterBiConsumers.put(
			"movementDate",
			(BiConsumer<MembershipActivity, Date>)
				MembershipActivity::setMovementDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMembershipActivityId() {
		return _membershipActivityId;
	}

	@Override
	public void setMembershipActivityId(long membershipActivityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_membershipActivityId = membershipActivityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getActionUserId() {
		return _actionUserId;
	}

	@Override
	public void setActionUserId(long actionUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actionUserId = actionUserId;
	}

	@Override
	public String getActionUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getActionUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setActionUserUuid(String actionUserUuid) {
	}

	@Override
	public String getTargetUserIds() {
		if (_targetUserIds == null) {
			return "";
		}
		else {
			return _targetUserIds;
		}
	}

	@Override
	public void setTargetUserIds(String targetUserIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_targetUserIds = targetUserIds;
	}

	@Override
	public boolean getIncoming() {
		return _incoming;
	}

	@Override
	public boolean isIncoming() {
		return _incoming;
	}

	@Override
	public void setIncoming(boolean incoming) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_incoming = incoming;
	}

	@Override
	public Date getMovementDate() {
		return _movementDate;
	}

	@Override
	public void setMovementDate(Date movementDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movementDate = movementDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, MembershipActivity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MembershipActivity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MembershipActivity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MembershipActivityImpl membershipActivityImpl =
			new MembershipActivityImpl();

		membershipActivityImpl.setMembershipActivityId(
			getMembershipActivityId());
		membershipActivityImpl.setGroupId(getGroupId());
		membershipActivityImpl.setActionUserId(getActionUserId());
		membershipActivityImpl.setTargetUserIds(getTargetUserIds());
		membershipActivityImpl.setIncoming(isIncoming());
		membershipActivityImpl.setMovementDate(getMovementDate());

		membershipActivityImpl.resetOriginalValues();

		return membershipActivityImpl;
	}

	@Override
	public MembershipActivity cloneWithOriginalValues() {
		MembershipActivityImpl membershipActivityImpl =
			new MembershipActivityImpl();

		membershipActivityImpl.setMembershipActivityId(
			this.<Long>getColumnOriginalValue("membershipActivityId"));
		membershipActivityImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		membershipActivityImpl.setActionUserId(
			this.<Long>getColumnOriginalValue("actionUserId"));
		membershipActivityImpl.setTargetUserIds(
			this.<String>getColumnOriginalValue("targetUserIds"));
		membershipActivityImpl.setIncoming(
			this.<Boolean>getColumnOriginalValue("incoming"));
		membershipActivityImpl.setMovementDate(
			this.<Date>getColumnOriginalValue("movementDate"));

		return membershipActivityImpl;
	}

	@Override
	public int compareTo(MembershipActivity membershipActivity) {
		long primaryKey = membershipActivity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MembershipActivity)) {
			return false;
		}

		MembershipActivity membershipActivity = (MembershipActivity)object;

		long primaryKey = membershipActivity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MembershipActivity> toCacheModel() {
		MembershipActivityCacheModel membershipActivityCacheModel =
			new MembershipActivityCacheModel();

		membershipActivityCacheModel.membershipActivityId =
			getMembershipActivityId();

		membershipActivityCacheModel.groupId = getGroupId();

		membershipActivityCacheModel.actionUserId = getActionUserId();

		membershipActivityCacheModel.targetUserIds = getTargetUserIds();

		String targetUserIds = membershipActivityCacheModel.targetUserIds;

		if ((targetUserIds != null) && (targetUserIds.length() == 0)) {
			membershipActivityCacheModel.targetUserIds = null;
		}

		membershipActivityCacheModel.incoming = isIncoming();

		Date movementDate = getMovementDate();

		if (movementDate != null) {
			membershipActivityCacheModel.movementDate = movementDate.getTime();
		}
		else {
			membershipActivityCacheModel.movementDate = Long.MIN_VALUE;
		}

		return membershipActivityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MembershipActivity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MembershipActivity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MembershipActivity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MembershipActivity)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MembershipActivity>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MembershipActivity.class, ModelWrapper.class);

	}

	private long _membershipActivityId;
	private long _groupId;
	private long _actionUserId;
	private String _targetUserIds;
	private boolean _incoming;
	private Date _movementDate;

	public <T> T getColumnValue(String columnName) {
		Function<MembershipActivity, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MembershipActivity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"membershipActivityId", _membershipActivityId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("actionUserId", _actionUserId);
		_columnOriginalValues.put("targetUserIds", _targetUserIds);
		_columnOriginalValues.put("incoming", _incoming);
		_columnOriginalValues.put("movementDate", _movementDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("membershipActivityId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("actionUserId", 4L);

		columnBitmasks.put("targetUserIds", 8L);

		columnBitmasks.put("incoming", 16L);

		columnBitmasks.put("movementDate", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MembershipActivity _escapedModel;

}