/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.application.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DefaultRole service. Represents a row in the &quot;Application_DefaultRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.facile.application.model.impl.DefaultRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.facile.application.model.impl.DefaultRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DefaultRole
 * @generated
 */
@ProviderType
public interface DefaultRoleModel extends BaseModel<DefaultRole> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a default role model instance should use the {@link DefaultRole} interface instead.
	 */

	/**
	 * Returns the primary key of this default role.
	 *
	 * @return the primary key of this default role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this default role.
	 *
	 * @param primaryKey the primary key of this default role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the default role ID of this default role.
	 *
	 * @return the default role ID of this default role
	 */
	public long getDefaultRoleId();

	/**
	 * Sets the default role ID of this default role.
	 *
	 * @param defaultRoleId the default role ID of this default role
	 */
	public void setDefaultRoleId(long defaultRoleId);

	/**
	 * Returns the role ID of this default role.
	 *
	 * @return the role ID of this default role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this default role.
	 *
	 * @param roleId the role ID of this default role
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the application ID of this default role.
	 *
	 * @return the application ID of this default role
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this default role.
	 *
	 * @param applicationId the application ID of this default role
	 */
	public void setApplicationId(long applicationId);

	@Override
	public DefaultRole cloneWithOriginalValues();

}