/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContentBlock service. Represents a row in the &quot;Course_ContentBlock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.nero.course.model.impl.ContentBlockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.nero.course.model.impl.ContentBlockImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentBlock
 * @generated
 */
@ProviderType
public interface ContentBlockModel extends BaseModel<ContentBlock> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content block model instance should use the {@link ContentBlock} interface instead.
	 */

	/**
	 * Returns the primary key of this content block.
	 *
	 * @return the primary key of this content block
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content block.
	 *
	 * @param primaryKey the primary key of this content block
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the block ID of this content block.
	 *
	 * @return the block ID of this content block
	 */
	public long getBlockId();

	/**
	 * Sets the block ID of this content block.
	 *
	 * @param blockId the block ID of this content block
	 */
	public void setBlockId(long blockId);

	/**
	 * Returns the course item ID of this content block.
	 *
	 * @return the course item ID of this content block
	 */
	public long getCourseItemId();

	/**
	 * Sets the course item ID of this content block.
	 *
	 * @param courseItemId the course item ID of this content block
	 */
	public void setCourseItemId(long courseItemId);

	/**
	 * Returns the modification date of this content block.
	 *
	 * @return the modification date of this content block
	 */
	public Date getModificationDate();

	/**
	 * Sets the modification date of this content block.
	 *
	 * @param modificationDate the modification date of this content block
	 */
	public void setModificationDate(Date modificationDate);

	/**
	 * Returns the block name of this content block.
	 *
	 * @return the block name of this content block
	 */
	@AutoEscape
	public String getBlockName();

	/**
	 * Sets the block name of this content block.
	 *
	 * @param blockName the block name of this content block
	 */
	public void setBlockName(String blockName);

	/**
	 * Returns the block value of this content block.
	 *
	 * @return the block value of this content block
	 */
	@AutoEscape
	public String getBlockValue();

	/**
	 * Sets the block value of this content block.
	 *
	 * @param blockValue the block value of this content block
	 */
	public void setBlockValue(String blockValue);

	/**
	 * Returns the file entry ID of this content block.
	 *
	 * @return the file entry ID of this content block
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this content block.
	 *
	 * @param fileEntryId the file entry ID of this content block
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the block type of this content block.
	 *
	 * @return the block type of this content block
	 */
	public int getBlockType();

	/**
	 * Sets the block type of this content block.
	 *
	 * @param blockType the block type of this content block
	 */
	public void setBlockType(int blockType);

	/**
	 * Returns the order of this content block.
	 *
	 * @return the order of this content block
	 */
	public int getOrder();

	/**
	 * Sets the order of this content block.
	 *
	 * @param order the order of this content block
	 */
	public void setOrder(int order);

	@Override
	public ContentBlock cloneWithOriginalValues();

}