/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.schedule.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CDTSession service. Represents a row in the &quot;Schedule_CDTSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.facile.schedule.model.impl.CDTSessionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.facile.schedule.model.impl.CDTSessionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CDTSession
 * @generated
 */
@ProviderType
public interface CDTSessionModel extends BaseModel<CDTSession> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cdt session model instance should use the {@link CDTSession} interface instead.
	 */

	/**
	 * Returns the primary key of this cdt session.
	 *
	 * @return the primary key of this cdt session
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cdt session.
	 *
	 * @param primaryKey the primary key of this cdt session
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the session ID of this cdt session.
	 *
	 * @return the session ID of this cdt session
	 */
	public long getSessionId();

	/**
	 * Sets the session ID of this cdt session.
	 *
	 * @param sessionId the session ID of this cdt session
	 */
	public void setSessionId(long sessionId);

	/**
	 * Returns the start of this cdt session.
	 *
	 * @return the start of this cdt session
	 */
	public Date getStart();

	/**
	 * Sets the start of this cdt session.
	 *
	 * @param start the start of this cdt session
	 */
	public void setStart(Date start);

	/**
	 * Returns the end of this cdt session.
	 *
	 * @return the end of this cdt session
	 */
	public Date getEnd();

	/**
	 * Sets the end of this cdt session.
	 *
	 * @param end the end of this cdt session
	 */
	public void setEnd(Date end);

	/**
	 * Returns the slot of this cdt session.
	 *
	 * @return the slot of this cdt session
	 */
	public int getSlot();

	/**
	 * Sets the slot of this cdt session.
	 *
	 * @param slot the slot of this cdt session
	 */
	public void setSlot(int slot);

	/**
	 * Returns the full cours name of this cdt session.
	 *
	 * @return the full cours name of this cdt session
	 */
	@AutoEscape
	public String getFullCoursName();

	/**
	 * Sets the full cours name of this cdt session.
	 *
	 * @param fullCoursName the full cours name of this cdt session
	 */
	public void setFullCoursName(String fullCoursName);

	/**
	 * Returns the room of this cdt session.
	 *
	 * @return the room of this cdt session
	 */
	@AutoEscape
	public String getRoom();

	/**
	 * Sets the room of this cdt session.
	 *
	 * @param room the room of this cdt session
	 */
	public void setRoom(String room);

	/**
	 * Returns the subject of this cdt session.
	 *
	 * @return the subject of this cdt session
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this cdt session.
	 *
	 * @param subject the subject of this cdt session
	 */
	public void setSubject(String subject);

	/**
	 * Returns the group ID of this cdt session.
	 *
	 * @return the group ID of this cdt session
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cdt session.
	 *
	 * @param groupId the group ID of this cdt session
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the is manual of this cdt session.
	 *
	 * @return the is manual of this cdt session
	 */
	public boolean getIsManual();

	/**
	 * Returns <code>true</code> if this cdt session is is manual.
	 *
	 * @return <code>true</code> if this cdt session is is manual; <code>false</code> otherwise
	 */
	public boolean isIsManual();

	/**
	 * Sets whether this cdt session is is manual.
	 *
	 * @param isManual the is manual of this cdt session
	 */
	public void setIsManual(boolean isManual);

	@Override
	public CDTSession cloneWithOriginalValues();

}