/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.schedule.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.weprode.facile.schedule.service.persistence.SlotConfigurationPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SlotConfiguration service. Represents a row in the &quot;Schedule_SlotConfiguration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.facile.schedule.model.impl.SlotConfigurationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.facile.schedule.model.impl.SlotConfigurationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SlotConfiguration
 * @generated
 */
@ProviderType
public interface SlotConfigurationModel extends BaseModel<SlotConfiguration> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a slot configuration model instance should use the {@link SlotConfiguration} interface instead.
	 */

	/**
	 * Returns the primary key of this slot configuration.
	 *
	 * @return the primary key of this slot configuration
	 */
	public SlotConfigurationPK getPrimaryKey();

	/**
	 * Sets the primary key of this slot configuration.
	 *
	 * @param primaryKey the primary key of this slot configuration
	 */
	public void setPrimaryKey(SlotConfigurationPK primaryKey);

	/**
	 * Returns the school ID of this slot configuration.
	 *
	 * @return the school ID of this slot configuration
	 */
	public long getSchoolId();

	/**
	 * Sets the school ID of this slot configuration.
	 *
	 * @param schoolId the school ID of this slot configuration
	 */
	public void setSchoolId(long schoolId);

	/**
	 * Returns the slot number of this slot configuration.
	 *
	 * @return the slot number of this slot configuration
	 */
	public int getSlotNumber();

	/**
	 * Sets the slot number of this slot configuration.
	 *
	 * @param slotNumber the slot number of this slot configuration
	 */
	public void setSlotNumber(int slotNumber);

	/**
	 * Returns the session start hour of this slot configuration.
	 *
	 * @return the session start hour of this slot configuration
	 */
	@AutoEscape
	public String getSessionStartHour();

	/**
	 * Sets the session start hour of this slot configuration.
	 *
	 * @param sessionStartHour the session start hour of this slot configuration
	 */
	public void setSessionStartHour(String sessionStartHour);

	/**
	 * Returns the session end hour of this slot configuration.
	 *
	 * @return the session end hour of this slot configuration
	 */
	@AutoEscape
	public String getSessionEndHour();

	/**
	 * Sets the session end hour of this slot configuration.
	 *
	 * @param sessionEndHour the session end hour of this slot configuration
	 */
	public void setSessionEndHour(String sessionEndHour);

	@Override
	public SlotConfiguration cloneWithOriginalValues();

}