/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.progression.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.weprode.nero.progression.model.ProgressionFolder;
import com.weprode.nero.progression.service.ProgressionFolderService;
import com.weprode.nero.progression.service.ProgressionFolderServiceUtil;
import com.weprode.nero.progression.service.persistence.ItemAssignmentPersistence;
import com.weprode.nero.progression.service.persistence.ItemAttachedFilePersistence;
import com.weprode.nero.progression.service.persistence.ItemContentPersistence;
import com.weprode.nero.progression.service.persistence.ProgressionFolderPersistence;
import com.weprode.nero.progression.service.persistence.ProgressionItemPersistence;
import com.weprode.nero.progression.service.persistence.ProgressionPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the progression folder remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.weprode.nero.progression.service.impl.ProgressionFolderServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.weprode.nero.progression.service.impl.ProgressionFolderServiceImpl
 * @generated
 */
public abstract class ProgressionFolderServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, ProgressionFolderService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProgressionFolderService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ProgressionFolderServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProgressionFolderService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		progressionFolderService = (ProgressionFolderService)aopProxy;

		_setServiceUtilService(progressionFolderService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProgressionFolderService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProgressionFolder.class;
	}

	protected String getModelClassName() {
		return ProgressionFolder.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				progressionFolderPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		ProgressionFolderService progressionFolderService) {

		try {
			Field field = ProgressionFolderServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, progressionFolderService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected ItemAssignmentPersistence itemAssignmentPersistence;

	@Reference
	protected ItemAttachedFilePersistence itemAttachedFilePersistence;

	@Reference
	protected ItemContentPersistence itemContentPersistence;

	@Reference
	protected ProgressionPersistence progressionPersistence;

	@Reference
	protected com.weprode.nero.progression.service.ProgressionFolderLocalService
		progressionFolderLocalService;

	protected ProgressionFolderService progressionFolderService;

	@Reference
	protected ProgressionFolderPersistence progressionFolderPersistence;

	@Reference
	protected ProgressionItemPersistence progressionItemPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}