/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.organization.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.organization.model.ClassCoursMapping;
import com.weprode.nero.organization.model.ClassCoursMappingModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ClassCoursMapping service. Represents a row in the &quot;Organization_ClassCoursMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ClassCoursMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClassCoursMappingImpl}.
 * </p>
 *
 * @author Marc Salvat
 * @see ClassCoursMappingImpl
 * @generated
 */
public class ClassCoursMappingModelImpl
	extends BaseModelImpl<ClassCoursMapping> implements ClassCoursMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a class cours mapping model instance should use the <code>ClassCoursMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "Organization_ClassCoursMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"mappingId", Types.BIGINT}, {"classOrgId", Types.BIGINT},
		{"coursOrgId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mappingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classOrgId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("coursOrgId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Organization_ClassCoursMapping (mappingId LONG not null primary key,classOrgId LONG,coursOrgId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Organization_ClassCoursMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY classCoursMapping.mappingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Organization_ClassCoursMapping.mappingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSORGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COURSORGID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MAPPINGID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ClassCoursMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mappingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMappingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mappingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ClassCoursMapping.class;
	}

	@Override
	public String getModelClassName() {
		return ClassCoursMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ClassCoursMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ClassCoursMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ClassCoursMapping, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ClassCoursMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ClassCoursMapping, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ClassCoursMapping, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ClassCoursMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ClassCoursMapping, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ClassCoursMapping, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ClassCoursMapping, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ClassCoursMapping, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ClassCoursMapping, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ClassCoursMapping, Object>>();
		Map<String, BiConsumer<ClassCoursMapping, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ClassCoursMapping, ?>>();

		attributeGetterFunctions.put(
			"mappingId", ClassCoursMapping::getMappingId);
		attributeSetterBiConsumers.put(
			"mappingId",
			(BiConsumer<ClassCoursMapping, Long>)
				ClassCoursMapping::setMappingId);
		attributeGetterFunctions.put(
			"classOrgId", ClassCoursMapping::getClassOrgId);
		attributeSetterBiConsumers.put(
			"classOrgId",
			(BiConsumer<ClassCoursMapping, Long>)
				ClassCoursMapping::setClassOrgId);
		attributeGetterFunctions.put(
			"coursOrgId", ClassCoursMapping::getCoursOrgId);
		attributeSetterBiConsumers.put(
			"coursOrgId",
			(BiConsumer<ClassCoursMapping, Long>)
				ClassCoursMapping::setCoursOrgId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMappingId() {
		return _mappingId;
	}

	@Override
	public void setMappingId(long mappingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mappingId = mappingId;
	}

	@Override
	public long getClassOrgId() {
		return _classOrgId;
	}

	@Override
	public void setClassOrgId(long classOrgId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classOrgId = classOrgId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassOrgId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classOrgId"));
	}

	@Override
	public long getCoursOrgId() {
		return _coursOrgId;
	}

	@Override
	public void setCoursOrgId(long coursOrgId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coursOrgId = coursOrgId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCoursOrgId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("coursOrgId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ClassCoursMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ClassCoursMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ClassCoursMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClassCoursMappingImpl classCoursMappingImpl =
			new ClassCoursMappingImpl();

		classCoursMappingImpl.setMappingId(getMappingId());
		classCoursMappingImpl.setClassOrgId(getClassOrgId());
		classCoursMappingImpl.setCoursOrgId(getCoursOrgId());

		classCoursMappingImpl.resetOriginalValues();

		return classCoursMappingImpl;
	}

	@Override
	public ClassCoursMapping cloneWithOriginalValues() {
		ClassCoursMappingImpl classCoursMappingImpl =
			new ClassCoursMappingImpl();

		classCoursMappingImpl.setMappingId(
			this.<Long>getColumnOriginalValue("mappingId"));
		classCoursMappingImpl.setClassOrgId(
			this.<Long>getColumnOriginalValue("classOrgId"));
		classCoursMappingImpl.setCoursOrgId(
			this.<Long>getColumnOriginalValue("coursOrgId"));

		return classCoursMappingImpl;
	}

	@Override
	public int compareTo(ClassCoursMapping classCoursMapping) {
		long primaryKey = classCoursMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ClassCoursMapping)) {
			return false;
		}

		ClassCoursMapping classCoursMapping = (ClassCoursMapping)object;

		long primaryKey = classCoursMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ClassCoursMapping> toCacheModel() {
		ClassCoursMappingCacheModel classCoursMappingCacheModel =
			new ClassCoursMappingCacheModel();

		classCoursMappingCacheModel.mappingId = getMappingId();

		classCoursMappingCacheModel.classOrgId = getClassOrgId();

		classCoursMappingCacheModel.coursOrgId = getCoursOrgId();

		return classCoursMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ClassCoursMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ClassCoursMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ClassCoursMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ClassCoursMapping)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ClassCoursMapping>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ClassCoursMapping.class, ModelWrapper.class);

	}

	private long _mappingId;
	private long _classOrgId;
	private long _coursOrgId;

	public <T> T getColumnValue(String columnName) {
		Function<ClassCoursMapping, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ClassCoursMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mappingId", _mappingId);
		_columnOriginalValues.put("classOrgId", _classOrgId);
		_columnOriginalValues.put("coursOrgId", _coursOrgId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mappingId", 1L);

		columnBitmasks.put("classOrgId", 2L);

		columnBitmasks.put("coursOrgId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ClassCoursMapping _escapedModel;

}