/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.school.life.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.weprode.nero.school.life.service.persistence.SessionStudentPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SessionStudent service. Represents a row in the &quot;Schoollife_SessionStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.weprode.nero.school.life.model.impl.SessionStudentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.weprode.nero.school.life.model.impl.SessionStudentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SessionStudent
 * @generated
 */
@ProviderType
public interface SessionStudentModel extends BaseModel<SessionStudent> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a session student model instance should use the {@link SessionStudent} interface instead.
	 */

	/**
	 * Returns the primary key of this session student.
	 *
	 * @return the primary key of this session student
	 */
	public SessionStudentPK getPrimaryKey();

	/**
	 * Sets the primary key of this session student.
	 *
	 * @param primaryKey the primary key of this session student
	 */
	public void setPrimaryKey(SessionStudentPK primaryKey);

	/**
	 * Returns the schoollife session ID of this session student.
	 *
	 * @return the schoollife session ID of this session student
	 */
	public long getSchoollifeSessionId();

	/**
	 * Sets the schoollife session ID of this session student.
	 *
	 * @param schoollifeSessionId the schoollife session ID of this session student
	 */
	public void setSchoollifeSessionId(long schoollifeSessionId);

	/**
	 * Returns the student ID of this session student.
	 *
	 * @return the student ID of this session student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this session student.
	 *
	 * @param studentId the student ID of this session student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the source teacher ID of this session student.
	 *
	 * @return the source teacher ID of this session student
	 */
	public long getSourceTeacherId();

	/**
	 * Sets the source teacher ID of this session student.
	 *
	 * @param sourceTeacherId the source teacher ID of this session student
	 */
	public void setSourceTeacherId(long sourceTeacherId);

	/**
	 * Returns the is present of this session student.
	 *
	 * @return the is present of this session student
	 */
	public boolean getIsPresent();

	/**
	 * Returns <code>true</code> if this session student is is present.
	 *
	 * @return <code>true</code> if this session student is is present; <code>false</code> otherwise
	 */
	public boolean isIsPresent();

	/**
	 * Sets whether this session student is is present.
	 *
	 * @param isPresent the is present of this session student
	 */
	public void setIsPresent(boolean isPresent);

	/**
	 * Returns the notify parents of this session student.
	 *
	 * @return the notify parents of this session student
	 */
	public boolean getNotifyParents();

	/**
	 * Returns <code>true</code> if this session student is notify parents.
	 *
	 * @return <code>true</code> if this session student is notify parents; <code>false</code> otherwise
	 */
	public boolean isNotifyParents();

	/**
	 * Sets whether this session student is notify parents.
	 *
	 * @param notifyParents the notify parents of this session student
	 */
	public void setNotifyParents(boolean notifyParents);

	/**
	 * Returns the comment of this session student.
	 *
	 * @return the comment of this session student
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this session student.
	 *
	 * @param comment the comment of this session student
	 */
	public void setComment(String comment);

	/**
	 * Returns the subject of this session student.
	 *
	 * @return the subject of this session student
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this session student.
	 *
	 * @param subject the subject of this session student
	 */
	public void setSubject(String subject);

	@Override
	public SessionStudent cloneWithOriginalValues();

}