/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.facile.organization.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.facile.organization.model.OrgMapping;
import com.weprode.facile.organization.model.OrgMappingModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OrgMapping service. Represents a row in the &quot;Organization_OrgMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OrgMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrgMappingImpl}.
 * </p>
 *
 * @author Marc Salvat
 * @see OrgMappingImpl
 * @generated
 */
public class OrgMappingModelImpl
	extends BaseModelImpl<OrgMapping> implements OrgMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a org mapping model instance should use the <code>OrgMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "Organization_OrgMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"organizationId", Types.BIGINT}, {"entStructureUAI", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entStructureUAI", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Organization_OrgMapping (organizationId LONG,entStructureUAI VARCHAR(75) not null primary key)";

	public static final String TABLE_SQL_DROP =
		"drop table Organization_OrgMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY orgMapping.entStructureUAI ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Organization_OrgMapping.entStructureUAI ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORGANIZATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTSTRUCTUREUAI_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OrgMappingModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _entStructureUAI;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setEntStructureUAI(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entStructureUAI;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return OrgMapping.class;
	}

	@Override
	public String getModelClassName() {
		return OrgMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OrgMapping, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OrgMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrgMapping, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OrgMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OrgMapping, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OrgMapping, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OrgMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OrgMapping, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OrgMapping, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OrgMapping, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OrgMapping, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OrgMapping, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OrgMapping, Object>>();
		Map<String, BiConsumer<OrgMapping, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OrgMapping, ?>>();

		attributeGetterFunctions.put(
			"organizationId", OrgMapping::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<OrgMapping, Long>)OrgMapping::setOrganizationId);
		attributeGetterFunctions.put(
			"entStructureUAI", OrgMapping::getEntStructureUAI);
		attributeSetterBiConsumers.put(
			"entStructureUAI",
			(BiConsumer<OrgMapping, String>)OrgMapping::setEntStructureUAI);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("organizationId"));
	}

	@Override
	public String getEntStructureUAI() {
		if (_entStructureUAI == null) {
			return "";
		}
		else {
			return _entStructureUAI;
		}
	}

	@Override
	public void setEntStructureUAI(String entStructureUAI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entStructureUAI = entStructureUAI;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public OrgMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OrgMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OrgMappingImpl orgMappingImpl = new OrgMappingImpl();

		orgMappingImpl.setOrganizationId(getOrganizationId());
		orgMappingImpl.setEntStructureUAI(getEntStructureUAI());

		orgMappingImpl.resetOriginalValues();

		return orgMappingImpl;
	}

	@Override
	public OrgMapping cloneWithOriginalValues() {
		OrgMappingImpl orgMappingImpl = new OrgMappingImpl();

		orgMappingImpl.setOrganizationId(
			this.<Long>getColumnOriginalValue("organizationId"));
		orgMappingImpl.setEntStructureUAI(
			this.<String>getColumnOriginalValue("entStructureUAI"));

		return orgMappingImpl;
	}

	@Override
	public int compareTo(OrgMapping orgMapping) {
		String primaryKey = orgMapping.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OrgMapping)) {
			return false;
		}

		OrgMapping orgMapping = (OrgMapping)object;

		String primaryKey = orgMapping.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OrgMapping> toCacheModel() {
		OrgMappingCacheModel orgMappingCacheModel = new OrgMappingCacheModel();

		orgMappingCacheModel.organizationId = getOrganizationId();

		orgMappingCacheModel.entStructureUAI = getEntStructureUAI();

		String entStructureUAI = orgMappingCacheModel.entStructureUAI;

		if ((entStructureUAI != null) && (entStructureUAI.length() == 0)) {
			orgMappingCacheModel.entStructureUAI = null;
		}

		return orgMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OrgMapping, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OrgMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrgMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((OrgMapping)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OrgMapping>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OrgMapping.class, ModelWrapper.class);

	}

	private long _organizationId;
	private String _entStructureUAI;

	public <T> T getColumnValue(String columnName) {
		Function<OrgMapping, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OrgMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("entStructureUAI", _entStructureUAI);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("organizationId", 1L);

		columnBitmasks.put("entStructureUAI", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OrgMapping _escapedModel;

}