/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.weprode.nero.application.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.weprode.nero.application.model.BroadcastRule;
import com.weprode.nero.application.model.BroadcastRuleModel;
import com.weprode.nero.application.model.BroadcastRuleSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BroadcastRule service. Represents a row in the &quot;Application_BroadcastRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BroadcastRuleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BroadcastRuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BroadcastRuleImpl
 * @generated
 */
@JSON(strict = true)
public class BroadcastRuleModelImpl
	extends BaseModelImpl<BroadcastRule> implements BroadcastRuleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a broadcast rule model instance should use the <code>BroadcastRule</code> interface instead.
	 */
	public static final String TABLE_NAME = "Application_BroadcastRule";

	public static final Object[][] TABLE_COLUMNS = {
		{"broadcastRuleId", Types.BIGINT}, {"applicationId", Types.BIGINT},
		{"schoolId", Types.BIGINT}, {"roleId", Types.BIGINT},
		{"orgId", Types.BIGINT}, {"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("broadcastRuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applicationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("schoolId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orgId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Application_BroadcastRule (broadcastRuleId LONG not null primary key,applicationId LONG,schoolId LONG,roleId LONG,orgId LONG,groupId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Application_BroadcastRule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY broadcastRule.broadcastRuleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Application_BroadcastRule.broadcastRuleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPLICATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SCHOOLID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BROADCASTRULEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static BroadcastRule toModel(BroadcastRuleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BroadcastRule model = new BroadcastRuleImpl();

		model.setBroadcastRuleId(soapModel.getBroadcastRuleId());
		model.setApplicationId(soapModel.getApplicationId());
		model.setSchoolId(soapModel.getSchoolId());
		model.setRoleId(soapModel.getRoleId());
		model.setOrgId(soapModel.getOrgId());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<BroadcastRule> toModels(BroadcastRuleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BroadcastRule> models = new ArrayList<BroadcastRule>(
			soapModels.length);

		for (BroadcastRuleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public BroadcastRuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _broadcastRuleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBroadcastRuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _broadcastRuleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BroadcastRule.class;
	}

	@Override
	public String getModelClassName() {
		return BroadcastRule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BroadcastRule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BroadcastRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BroadcastRule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BroadcastRule)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BroadcastRule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BroadcastRule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BroadcastRule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BroadcastRule, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BroadcastRule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, BroadcastRule>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			BroadcastRule.class.getClassLoader(), BroadcastRule.class,
			ModelWrapper.class);

		try {
			Constructor<BroadcastRule> constructor =
				(Constructor<BroadcastRule>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<BroadcastRule, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BroadcastRule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BroadcastRule, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<BroadcastRule, Object>>();
		Map<String, BiConsumer<BroadcastRule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<BroadcastRule, ?>>();

		attributeGetterFunctions.put(
			"broadcastRuleId", BroadcastRule::getBroadcastRuleId);
		attributeSetterBiConsumers.put(
			"broadcastRuleId",
			(BiConsumer<BroadcastRule, Long>)BroadcastRule::setBroadcastRuleId);
		attributeGetterFunctions.put(
			"applicationId", BroadcastRule::getApplicationId);
		attributeSetterBiConsumers.put(
			"applicationId",
			(BiConsumer<BroadcastRule, Long>)BroadcastRule::setApplicationId);
		attributeGetterFunctions.put("schoolId", BroadcastRule::getSchoolId);
		attributeSetterBiConsumers.put(
			"schoolId",
			(BiConsumer<BroadcastRule, Long>)BroadcastRule::setSchoolId);
		attributeGetterFunctions.put("roleId", BroadcastRule::getRoleId);
		attributeSetterBiConsumers.put(
			"roleId",
			(BiConsumer<BroadcastRule, Long>)BroadcastRule::setRoleId);
		attributeGetterFunctions.put("orgId", BroadcastRule::getOrgId);
		attributeSetterBiConsumers.put(
			"orgId", (BiConsumer<BroadcastRule, Long>)BroadcastRule::setOrgId);
		attributeGetterFunctions.put("groupId", BroadcastRule::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<BroadcastRule, Long>)BroadcastRule::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBroadcastRuleId() {
		return _broadcastRuleId;
	}

	@Override
	public void setBroadcastRuleId(long broadcastRuleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_broadcastRuleId = broadcastRuleId;
	}

	@JSON
	@Override
	public long getApplicationId() {
		return _applicationId;
	}

	@Override
	public void setApplicationId(long applicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicationId = applicationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalApplicationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("applicationId"));
	}

	@JSON
	@Override
	public long getSchoolId() {
		return _schoolId;
	}

	@Override
	public void setSchoolId(long schoolId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_schoolId = schoolId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSchoolId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("schoolId"));
	}

	@JSON
	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	@JSON
	@Override
	public long getOrgId() {
		return _orgId;
	}

	@Override
	public void setOrgId(long orgId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orgId = orgId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BroadcastRule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BroadcastRule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BroadcastRule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BroadcastRuleImpl broadcastRuleImpl = new BroadcastRuleImpl();

		broadcastRuleImpl.setBroadcastRuleId(getBroadcastRuleId());
		broadcastRuleImpl.setApplicationId(getApplicationId());
		broadcastRuleImpl.setSchoolId(getSchoolId());
		broadcastRuleImpl.setRoleId(getRoleId());
		broadcastRuleImpl.setOrgId(getOrgId());
		broadcastRuleImpl.setGroupId(getGroupId());

		broadcastRuleImpl.resetOriginalValues();

		return broadcastRuleImpl;
	}

	@Override
	public BroadcastRule cloneWithOriginalValues() {
		BroadcastRuleImpl broadcastRuleImpl = new BroadcastRuleImpl();

		broadcastRuleImpl.setBroadcastRuleId(
			this.<Long>getColumnOriginalValue("broadcastRuleId"));
		broadcastRuleImpl.setApplicationId(
			this.<Long>getColumnOriginalValue("applicationId"));
		broadcastRuleImpl.setSchoolId(
			this.<Long>getColumnOriginalValue("schoolId"));
		broadcastRuleImpl.setRoleId(
			this.<Long>getColumnOriginalValue("roleId"));
		broadcastRuleImpl.setOrgId(this.<Long>getColumnOriginalValue("orgId"));
		broadcastRuleImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));

		return broadcastRuleImpl;
	}

	@Override
	public int compareTo(BroadcastRule broadcastRule) {
		long primaryKey = broadcastRule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BroadcastRule)) {
			return false;
		}

		BroadcastRule broadcastRule = (BroadcastRule)object;

		long primaryKey = broadcastRule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BroadcastRule> toCacheModel() {
		BroadcastRuleCacheModel broadcastRuleCacheModel =
			new BroadcastRuleCacheModel();

		broadcastRuleCacheModel.broadcastRuleId = getBroadcastRuleId();

		broadcastRuleCacheModel.applicationId = getApplicationId();

		broadcastRuleCacheModel.schoolId = getSchoolId();

		broadcastRuleCacheModel.roleId = getRoleId();

		broadcastRuleCacheModel.orgId = getOrgId();

		broadcastRuleCacheModel.groupId = getGroupId();

		return broadcastRuleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BroadcastRule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BroadcastRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BroadcastRule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BroadcastRule)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BroadcastRule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BroadcastRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BroadcastRule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BroadcastRule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BroadcastRule>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _broadcastRuleId;
	private long _applicationId;
	private long _schoolId;
	private long _roleId;
	private long _orgId;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		Function<BroadcastRule, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BroadcastRule)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("broadcastRuleId", _broadcastRuleId);
		_columnOriginalValues.put("applicationId", _applicationId);
		_columnOriginalValues.put("schoolId", _schoolId);
		_columnOriginalValues.put("roleId", _roleId);
		_columnOriginalValues.put("orgId", _orgId);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("broadcastRuleId", 1L);

		columnBitmasks.put("applicationId", 2L);

		columnBitmasks.put("schoolId", 4L);

		columnBitmasks.put("roleId", 8L);

		columnBitmasks.put("orgId", 16L);

		columnBitmasks.put("groupId", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BroadcastRule _escapedModel;

}